-- R__dev_seed_routing.sql — mockup 06's routing screen, as rows, in a development database
-- and nowhere else.
--
-- The fourth development seed, and it answers the fourth question. R__dev_seed.sql (#23) is
-- *who exists*, R__dev_seed_dashboard.sql (#68) is *what the loop has done*,
-- R__dev_seed_providers.sql (#221) is *what it is allowed to call*, and this is **how it
-- decides which one to call**. All of it belongs to `acme-robotics`, the workspace every
-- mockup is drawn in.
--
-- docs/mockups/06-model-routing.html draws five surfaces and two numeric columns, and this
-- file is every one of them but the first:
--
--   | Surface                     | Rows                                                  |
--   |-----------------------------|-------------------------------------------------------|
--   | Provider health strip       | `provider_connections.health` — #221's, and its alone |
--   | Routing matrix (8 rows)     | `task_kinds` × `routes` × the first two `route_hops`  |
--   | Route inspector             | `implement-primary`'s three hops and its policies     |
--   | Escalation rules (3 active) | `escalation_rules`, sentences generated by V018       |
--   | Spend by provider · 30d     | `token_usage`, aggregated — nothing stored            |
--   | `$/run avg` and `p50`       | `token_usage.task_kind` and `.latency_ms` (V020)      |
--
-- Filed as issue #192 (Y.4). The schema it fills is V015/V017 (aliases), V016 (kinds,
-- routes, hops), V018 (rules) and V010 as extended by V020 (the usage the stats are
-- computed from). Read by Z.5 (#198), Z.6 (#199), AA.2 (#201), AA.5 (#204) and AA.7 (#206).
--
-- ---------------------------------------------------------------------------
-- Decision M7, which is the whole reason this file is as long as it is.
-- ---------------------------------------------------------------------------
--
--   > `$/run`, p50 and spend are **computed** from `token_usage` + runs; no data → em-dash,
--   > never a fabricated number; local providers show `$0.00` only via real zero-price rows.
--
-- So `$0.87`, `41.0s`, `$412.80` and *"Local models served 31% of all tokens"* are **not**
-- seeded anywhere. There is no column on a route, an alias or a connection that any of them
-- could be written into, and this file writes none. What it seeds instead is the *usage*
-- those figures are aggregates of, arranged so the aggregation lands on the mockup.
--
-- That is a deliberately harder job than storing the answers, and it is the job because of
-- what storing them would cost: a `$/run` column filled by a seed leaves Z.5's aggregation
-- untested and M7's em-dash rule unverifiable. A number that was never computed cannot be
-- *absent* in the way the rule requires — the honest em-dash of a workspace with no data is
-- only observable if the populated workspace's figure was computed too.
--
-- **The arithmetic, in one table.** Each task kind is seeded a run of calls whose costs and
-- latencies are a symmetric arithmetic sequence around the mockup's figure — so the *mean*
-- of the costs is the `$/run avg` column exactly, and the *median* of the latencies is the
-- `p50 latency` column exactly, with no rounding anywhere:
--
--   | Task kind    | Calls | mean cost | `$/run avg` | median latency | `p50`  |
--   |--------------|------:|----------:|------------:|---------------:|-------:|
--   | `analyze`    |    25 |      4.00¢|       $0.04 |         3100ms |   3.1s |
--   | `estimate`   |    25 |      1.00¢|       $0.01 |         1200ms |   1.2s |
--   | `plan`       |    15 |     31.00¢|       $0.31 |         9800ms |   9.8s |
--   | `implement`  |    15 |     87.00¢|       $0.87 |        41000ms |  41.0s |
--   | `test-gen`   |    15 |     12.00¢|       $0.12 |        17400ms |  17.4s |
--   | `review`     |    15 |     22.00¢|       $0.22 |        12600ms |  12.6s |
--   | `docs`       |    15 |      0.00¢|       $0.00 |         6300ms |   6.3s |
--   | `commit-msg` |   245 |      0.00¢|       $0.00 |          800ms |   0.8s |
--
-- A symmetric sequence is what makes both exact at once. Offsets either side of the centre
-- cancel in a sum, so `avg(cost_cents)` is the centre; an odd number of calls puts one row
-- *at* the centre, so `percentile_cont(0.5)` is that row rather than an interpolation. The
-- spread is real variation — an `implement` call ranges 16.5s to 65.5s, and 24¢ to $1.50 —
-- which is what a median is worth having for.
--
-- ---------------------------------------------------------------------------
-- The four seeds share one ledger, and this one takes its spend out of #221's share.
-- ---------------------------------------------------------------------------
--
-- `token_usage` is one table and three of the four seeds write to it, so a row added here
-- moves a figure mockup 02 and mockup 07 already render. Two rules keep that from happening,
-- and both are asserted in tests/seed.sql:
--
--   1. **Nothing here lands on today.** Mockup 02's *Token spend · today* card is exactly
--      #68's twelve events; every row below is placed strictly before today's UTC midnight,
--      in the same window #221 uses and with the same first-of-the-month branch.
--
--   2. **The month meters do not move**, because #221 was reduced by exactly what this file
--      adds. Its header carries the arithmetic; the short form is that routed spend of
--      $22.25 (Anthropic) and $1.80 (Copilot) came out of that file's remainder rather than
--      on top of it, and 600 000 routed `docs` tokens came out of its Ollama share, so the
--      cards still read $412.80 / $64.10 / $76.00 and *2.1M tokens on-box*.
--
-- **What the 30-day card therefore reads, and where the mockup does not close.** Every row
-- any seed writes falls inside the trailing thirty days, so *Spend by provider · 30d* is the
-- calendar-month figure on every day of the month:
--
--   | Provider                | Seeded 30d | Mockup 06 | Mockup 07 (month) |
--   |-------------------------|-----------:|----------:|------------------:|
--   | Anthropic               |    $412.80 |   $412.80 |           $412.80 |
--   | GitHub Copilot          |     $76.00 |    $96.40 |            $76.00 |
--   | Cursor                  |     $64.10 |    $54.10 |            $64.10 |
--   | Local (vLLM + Ollama)   |      $0.00 |     $0.00 |             $0.00 |
--
-- The two disagreements are the mockups', not the seed's, and one of them is **not
-- reachable by any seed at all**: thirty days is a superset of month-to-date, so a 30-day
-- total can never be *less* than the month total inside it, and mockup 06 asks Cursor to be
-- $10.00 lower than mockup 07's card for the same rows. Copilot's $96.40 would need $20.40
-- dated before the month began — a window that is twenty-nine days wide on the 2nd and
-- **empty** on the 31st, which would make the card's figure depend on the date.
--
-- So this file seeds the reading both screens can hold at once, and states the discrepancy
-- here rather than leaving Z.5 (#198) to find it against a fixture that will not add up —
-- the same courtesy R__dev_seed_dashboard.sql pays where mockup 02's merge rate does not
-- close. Anthropic and the local `$0.00` land on the mockup exactly; Copilot and Cursor land
-- on mockup 07's, and #192's PR asks for the design to be amended to them.
--
-- ---------------------------------------------------------------------------
-- Zero-priced is not unpriced, and the difference is seeded in one workspace.
-- ---------------------------------------------------------------------------
--
-- `docs` and `commit-msg` route to local models, and their `$0.00` in the matrix — and the
-- local provider's `$0.00` on the spend card — is only honest if the calls were **priced,
-- and priced at nothing**. Their rows therefore carry `cost_cents = 0`, which is a recorded
-- fact about a call that cost nothing.
--
-- #68's and #221's Ollama rows carry `null` instead, which says the other thing: *nobody
-- priced this*. Both states now exist in `acme-robotics`, which is what makes DASH-J.4's
-- (#92) rule testable — a re-pricing pass must fill the nulls and leave the zeros alone, and
-- a stats service must render `$0.00` for one and `unpriced` for the other. Seeding only one
-- of the two would have left the distinction as a sentence in a header.
--
-- **The local token share is the same rule counted rather than summed.** *"Local models
-- served 31% of all tokens"* is `tokens on the two local kinds / all tokens` over the same
-- thirty days, and it lands on exactly 31% because the pieces were chosen to:
--
--   |                       | Cloud tokens | Local tokens |
--   |-----------------------|-------------:|-------------:|
--   | #68 — today           |    3 700 000 |      500 000 |
--   | #221 — earlier        |   33 400 000 |    1 000 000 |
--   | here — routed calls   |   11 200 000 |   20 200 000 |
--   | **Total**             | **48 300 000** | **21 700 000** |
--
-- 21 700 000 of 70 000 000 is 31.0%, with no rounding. The local half is large because that
-- is what the claim means: a workstation that answers every commit message and every docs
-- pass serves a third of the tokens and none of the bill.
--
-- ---------------------------------------------------------------------------
-- No `runs` row is written here, and that is decision M7 read carefully.
-- ---------------------------------------------------------------------------
--
-- A `runs` row is a **loop** — one issue, from *Implementing* to *Merged* — and mockup 02's
-- *Loops live*, *PRs merged · 7d* and *Avg. cycle time* are counts and averages over the
-- fifty-three #68 seeds. A routing call is a *step inside* a loop, and there are 370 of them
-- below; writing one run per call would change every figure on the dashboard.
--
-- V020 is what makes that unnecessary: `task_kind` and `latency_ms` live on the ledger row,
-- which is already one row per call, so the matrix's two columns are aggregates over rows
-- this file writes and the dashboard's are aggregates over rows #68 wrote. `run_id` is left
-- null throughout — these calls belong to a *kind of work*, and inventing a mapping from 370
-- synthetic calls onto 53 loops would be a fixture nothing renders.
--
-- ---------------------------------------------------------------------------
-- Ids, and the three properties every seed here has.
-- ---------------------------------------------------------------------------
--
-- Six prefixes, on the convention R__dev_seed.sql set — an id beginning `5eed` came from a
-- seed, and the two hex digits after it say which table:
--
--   | Rows                     | Id                                                  |
--   |--------------------------|-----------------------------------------------------|
--   | `model_aliases` (7)      | `5eed000f-0000-4000-8000-` + ordinal 1–7            |
--   | `task_kinds` (8)         | `5eed0010-0000-4000-8000-` + matrix position 1–8    |
--   | `routes` (8)             | `5eed0011-0000-4000-8000-` + its kind's position    |
--   | `route_hops` (17)        | `5eed0012-0000-4000-8000-` + ordinal 1–17           |
--   | `escalation_rules` (3)   | `5eed0013-0000-4000-8000-` + card position 1–3      |
--   | `token_usage` (370)      | `5eed0014-0000-4000-8000-` + ordinal 1–370          |
--
-- The usage ids are computed from a per-kind base and the call's number rather than written
-- out, for the reason #68 computes its seventy-seven: a list of 370 literals is a list nobody
-- proof-reads. They are as deterministic as literals are — the same file yields the same
-- uuid on every machine and every pass — which is the property the convention is for.
-- `gen_random_uuid()` appears nowhere, and tests/seed.test.sh asserts it.
--
-- It **cannot run in production** (every statement ends `and ${ouro_dev_seed}`, which is
-- `false` in flyway.toml), it is **idempotent** (every id is derived from literals and every
-- statement ends `on conflict do nothing`), and it **never fails on a database somebody has
-- edited** (children find their parents by natural key — the workspace by slug, a connection
-- by its kind and name, a kind by its name, an alias by its alias). Three statements name
-- their arbiter as `on conflict (id)`: `task_kinds`, `route_hops` and `escalation_rules` all
-- carry a **deferrable** unique key, and PostgreSQL refuses a targetless `on conflict` on
-- such a table outright — the same accommodation #68 makes for `queue_items`.
--
-- **The personal workspace is deliberately empty.** `kensuenobu` gets no alias, no task kind,
-- no route and no usage row, exactly as it gets no run and no provider — which is what makes
-- it the fixture AA.6 (#205) renders *"set up your first route"* against, and the one M7's
-- em-dashes can be observed in: a workspace with no usage has no `$/run` to average and no
-- latency to take a median of, and both must render `—` rather than `$0.00` and `0.0s`.
--
-- ---------------------------------------------------------------------------
-- The seven aliases — the only place a raw model string is allowed to live.
--
-- Decision M1: routes name aliases, aliases name models, and `model_aliases.model_id` is the
-- one column in this schema where `claude-fable-5` may appear. Every hop below therefore
-- points at one of these seven rows, and swapping `coder-max` onto another model stays one
-- edit of one row.
--
-- Six are the matrix's; the seventh is `second-opinion`, which no route's chain contains and
-- the *security label* escalation rule names — Y.3 (#191) put that rule in the schema, so
-- the alias it adds a vote from has to exist here or the rule cannot be written at all.
-- It is the one row with a `restrictions` document: `review_vote_only`, because a vote is
-- exactly what this workspace allows it to be used for (V019, decision R3).
--
-- Each is bound by natural key to the connection that serves it — the kind and display name
-- #221 seeded — so no id from that file is repeated here. `enabled` is true on all seven:
-- V019's unbound state is mockup 21's fixture (CG.4, #582) and not this screen's.
--
-- `params` is `{}` throughout, which is the ordinary state. The mockup's one *"(max
-- thinking)"* belongs to the escalation rule that applies it, not to the alias — a rule's
-- params are merged over an alias's at resolution (Z.1), and seeding `thinking: max` onto
-- `coder-max` itself would make the rule a no-op that appears to work.
-- ---------------------------------------------------------------------------
insert into ouroboros.model_aliases
    (id, organization_id, alias, provider_connection_id, model_id, params,
     enabled, restrictions, updated_by)
select ('5eed000f-0000-4000-8000-' || lpad(seed.n::text, 12, '0'))::uuid,
       org."id", seed.alias, conn.id, seed.model_id, '{}'::jsonb,
       true, seed.restrictions::jsonb, person."id"
  from (values
         (1, 'coder-max',      'anthropic',         'Anthropic Claude',
          'claude-fable-5',   '{}'),
         (2, 'coder-std',      'anthropic',         'Anthropic Claude',
          'claude-sonnet-5',  '{}'),
         (3, 'sizer',          'anthropic',         'Anthropic Claude',
          'claude-haiku-4-5', '{}'),
         (4, 'coder-fallback', 'copilot',           'GitHub Copilot',
          'gpt-5-codex',      '{}'),
         (5, 'local-docs',     'ollama',            'Ollama · workstation',
          'qwen3-coder:32b',  '{}'),
         (6, 'local-free',     'openai_compatible', 'OpenAI-compatible · local vLLM',
          'llama-4-maverick', '{}'),
         (7, 'second-opinion', 'cursor',            'Cursor',
          'composer-2',       '{"review_vote_only": true}')
       ) as seed (n, alias, kind, display_name, model_id, restrictions)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  join ouroboros."user" person on person."email" = 'ken@acme-robotics.dev'
  join ouroboros.provider_connections conn
    on conn.organization_id = org."id"
   and conn.kind = seed.kind
   and conn.display_name = seed.display_name
 where ${ouro_dev_seed}
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- The eight task kinds — the matrix's rows, in the matrix's order.
--
-- `name` is the mono label the row prints and `description` is the grey line under it,
-- verbatim. `sort_order` is the order the mockup draws them in, which is the loop's own
-- order of operations: read the issue, size it, plan it, write it, test it, review it,
-- document it, commit it.
--
-- Stored rather than derived because it is a *workspace's* list: a team that never generates
-- tests deletes that row, and a team with a `triage` step adds one. Nothing here is a
-- vocabulary — V016 constrains the shape of a name, never the set of them.
-- ---------------------------------------------------------------------------
insert into ouroboros.task_kinds (id, organization_id, name, description, sort_order)
select ('5eed0010-0000-4000-8000-' || lpad(seed.sort_order::text, 12, '0'))::uuid,
       org."id", seed.name, seed.description, seed.sort_order
  from (values
         (1, 'analyze',    'Read the issue, map the affected code paths'),
         (2, 'estimate',   'Size effort XS–XL before queueing'),
         (3, 'plan',       'Decompose into steps, pick a workflow'),
         (4, 'implement',  'Write the change, run tests, iterate to green'),
         (5, 'test-gen',   'Generate unit and regression tests for the diff'),
         (6, 'review',     'Self-review the PR against the acceptance criteria'),
         (7, 'docs',       'Update READMEs, changelogs, operator manual'),
         (8, 'commit-msg', 'Conventional-commit message from the staged diff')
       ) as seed (sort_order, name, description)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
 where ${ouro_dev_seed}
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The eight routes — one per kind, and the inspector's three policies.
--
-- `tag` is the name the matrix prints as a pill and the inspector's title —
-- `implement-primary`. V016 makes it unique per workspace, so it is what a URL and an
-- explanation can name a route by without carrying a uuid.
--
-- **Only `implement-primary` carries a cost cap**, because it is the only route the mockup
-- opens: its inspector reads *Max cost per run* `$2.50`, which is `max_cost_cents_per_run =
-- 250`. The other seven are null — *no cap configured* — rather than 250 repeated eight
-- times, because a policy nobody set is not a policy, and a seed that quietly applies one
-- everywhere would make the inspector's field look like a display of a default.
--
-- `allow_local_fallback` is on everywhere, which is the mockup's switch and V016's default;
-- `floor_hop_index` is null everywhere, which is *"Fail run instead of degrading below
-- fallback 2"* switched **off**. Null rather than a number is what off means here: a floor is
-- a hop index, and there is no index that means "no floor".
--
-- `updated_by` is Ken, the person who owns the workspace — these are routes somebody saved,
-- which is what the *Save routes* button writes.
-- ---------------------------------------------------------------------------
insert into ouroboros.routes
    (id, organization_id, task_kind_id, tag, allow_local_fallback,
     floor_hop_index, max_cost_cents_per_run, updated_by)
select ('5eed0011-0000-4000-8000-' || lpad(seed.sort_order::text, 12, '0'))::uuid,
       org."id", kind.id, seed.tag, true, null, seed.max_cost_cents, person."id"
  from (values
         (1, 'analyze',    'analyze-primary',    null),
         (2, 'estimate',   'estimate-primary',   null),
         (3, 'plan',       'plan-primary',       null),
         (4, 'implement',  'implement-primary',  250),
         (5, 'test-gen',   'testgen-primary',    null),
         (6, 'review',     'review-primary',     null),
         (7, 'docs',       'docs-primary',       null),
         (8, 'commit-msg', 'commitmsg-primary',  null)
       ) as seed (sort_order, kind_name, tag, max_cost_cents)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  join ouroboros.task_kinds kind
    on kind.organization_id = org."id" and kind.name = seed.kind_name
  join ouroboros."user" person on person."email" = 'ken@acme-robotics.dev'
 where ${ouro_dev_seed}
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- The seventeen hops — the chains, in order.
--
-- The matrix shows a route's first two hops as its *Primary model* and *Fallback* columns;
-- the inspector shows the whole chain, which is why `implement-primary` has three and the
-- other seven have two. `position` is dense from 1 within each route, which V016 makes a
-- correctness rule rather than a convention — `floor_hop_index` is a statement about a hop
-- *number*, and a chain numbered 1, 2, 5 makes *"fail instead of degrading below fallback
-- 2"* mean nothing.
--
-- **`note` is written where the mockup writes prose and left null where it composes one.**
-- The inspector's hop 2 and hop 3 print *"Fallback on 5xx / timeouts"* and *"Offline mode —
-- keeps the loop turning without a network"*, which are an operator's sentences and are
-- stored. Hop 1 prints *"Primary · API key valid, 42ms to us-east"*, which is not: *Primary*
-- is position 1, *API key valid* is the connection's status, and `42ms` is
-- `health.latency_ms` measured minutes ago. Storing that sentence would freeze a latency
-- into a note and make the chip and the hop disagree the first time a check ran.
--
-- The other seven routes have no notes at all, which is the ordinary state — V016 made the
-- column nullable for it, and a seed that invented a sentence per hop would be putting words
-- in an operator's mouth.
-- ---------------------------------------------------------------------------
insert into ouroboros.route_hops
    (id, organization_id, route_id, position, model_alias_id, note)
select ('5eed0012-0000-4000-8000-' || lpad(seed.n::text, 12, '0'))::uuid,
       org."id", route.id, seed.position, alias.id, seed.note
  from (values
         ( 1, 'analyze-primary',   1, 'coder-std',      null),
         ( 2, 'analyze-primary',   2, 'local-docs',     null),
         ( 3, 'estimate-primary',  1, 'sizer',          null),
         ( 4, 'estimate-primary',  2, 'local-free',     null),
         ( 5, 'plan-primary',      1, 'coder-max',      null),
         ( 6, 'plan-primary',      2, 'coder-std',      null),
         ( 7, 'implement-primary', 1, 'coder-max',      null),
         ( 8, 'implement-primary', 2, 'coder-fallback', 'Fallback on 5xx / timeouts'),
         ( 9, 'implement-primary', 3, 'local-docs',
          'Offline mode — keeps the loop turning without a network'),
         (10, 'testgen-primary',   1, 'coder-fallback', null),
         (11, 'testgen-primary',   2, 'coder-std',      null),
         (12, 'review-primary',    1, 'coder-max',      null),
         (13, 'review-primary',    2, 'coder-std',      null),
         (14, 'docs-primary',      1, 'local-docs',     null),
         (15, 'docs-primary',      2, 'sizer',          null),
         (16, 'commitmsg-primary', 1, 'local-free',     null),
         (17, 'commitmsg-primary', 2, 'sizer',          null)
       ) as seed (n, tag, position, alias, note)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  join ouroboros.routes route
    on route.organization_id = org."id" and route.tag = seed.tag
  join ouroboros.model_aliases alias
    on alias.organization_id = org."id" and alias.alias = seed.alias
 where ${ouro_dev_seed}
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The three escalation rules — `3 active`.
--
-- Structure, never sentences. `display` is a **stored generated column** (V018): PostgreSQL
-- derives the card's line from `"when"` and `"then"` and refuses a hand-written one, so the
-- three rows below produce the mockup's three sentences character for character without this
-- file spelling any of them:
--
--   `{"effort_gte": "l"}` + `{"use_alias": {…, "params": {"thinking": "max"}}}`
--     ─▶ effort ≥ L → implement uses coder-max (max thinking)
--   `{"label": "security"}` + `{"add_vote": {…}}`
--     ─▶ security label → review adds second-opinion vote
--   `{"diff_kind": "docs_only"}` + `{"route_local": {}}`
--     ─▶ docs-only diff → everything routes local
--
-- The mockup's *"(max thinking)"* is `params` on the rule rather than prose, which is what
-- lets Z.1 (#194) merge it over the alias's params instead of parsing a phrase.
--
-- `escalation_rule_targets_exist()` is a **deferred** constraint trigger over the task kind
-- and alias these documents name — neither is reachable by a foreign key, because both live
-- inside jsonb. Deferral is what lets this statement run in any order relative to the two
-- above; it is checked at commit, when all three tables are populated.
--
-- **One mockup inconsistency worth knowing about.** The matrix draws the first rule's summary
-- on the `plan` row and the second's on `review`, while the rules card says the first rule
-- modifies `implement`. Y.3 (#191) settled that in the schema's favour — its `then` names
-- `implement`, and tests/constraints.sql asserts the sentence — so the matrix's *Escalation*
-- column, computed from these rows, shows the rule on `implement` and an em-dash on `plan`.
-- That is the structure the card and the matrix now share; the mockup drew them separately.
-- ---------------------------------------------------------------------------
insert into ouroboros.escalation_rules
    (id, organization_id, enabled, sort_order, "when", "then")
select ('5eed0013-0000-4000-8000-' || lpad(seed.sort_order::text, 12, '0'))::uuid,
       org."id", true, seed.sort_order, seed.rule_when::jsonb, seed.rule_then::jsonb
  from (values
         (1, '{"effort_gte": "l"}',
             '{"use_alias": {"task_kind": "implement", "alias": "coder-max",'
             || ' "params": {"thinking": "max"}}}'),
         (2, '{"label": "security"}',
             '{"add_vote": {"task_kind": "review", "alias": "second-opinion"}}'),
         (3, '{"diff_kind": "docs_only"}',
             '{"route_local": {}}')
       ) as seed (sort_order, rule_when, rule_then)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
 where ${ouro_dev_seed}
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The 370 routed calls — everything the matrix's two numeric columns are made of.
--
-- One row per model call, which is the grain V010 chose and the grain both figures are
-- about. `task_kind` says which matrix row a call belongs to and `latency_ms` how long it
-- took (V020); `provider` and `model` are the connection and model its route's **primary**
-- hop resolves to, which is what a call that succeeded on its first hop records.
--
-- **The three sequences.** For a kind with `calls` rows, call `n` records
--
--   cost_cents = centre_cost    + (n − centre) × cost_step
--   latency_ms = centre_latency + (n − centre) × latency_step
--   tokens     = centre_tokens  + (n − centre) × token_step
--
-- with `centre = (calls + 1) / 2`. The offsets are symmetric, so each column's *mean* is its
-- centre — which makes `avg(cost_cents)` the `$/run avg` column exactly — and `calls` is odd,
-- so one row sits **at** the centre and `percentile_cont(0.5)` returns it rather than an
-- interpolation between two neighbours. Token totals are `calls × centre_tokens` for the same
-- reason, which is what makes the 31% share above land on a whole number.
--
-- Every centre is a multiple of five and every step divides it, so `tokens_in` and
-- `tokens_out` — four fifths and one fifth, as both earlier seeds split them — add back up to
-- the total with nothing lost to integer division.
--
-- **`cost_cents = 0` on the two local kinds, and it is not a null.** See the header: zero is
-- a price that was recorded, null is a price nobody recorded, and this workspace now holds
-- both so the difference is testable rather than asserted.
--
-- **The window** is #221's, for the reason its header gives: `occurred_at` is
-- `start + (today 00:00 − start) × n/(calls + 1)`, so every call lands strictly inside
-- `[start, today 00:00 UTC)` and none on either edge. `start` is the later of the month's
-- first instant and thirteen days ago — except on the first of a month, when *earlier this
-- month* is an empty range and the window is yesterday instead. On that one day the month
-- meters read the day's spend alone, exactly as they do without this file; the 30-day card
-- and the per-kind statistics are unaffected, because a window of thirteen days and a window
-- of one are both inside thirty.
-- ---------------------------------------------------------------------------
insert into ouroboros.token_usage
    (id, organization_id, run_id, provider, model, tokens_in, tokens_out,
     cost_cents, occurred_at, task_kind, latency_ms)
select ('5eed0014-0000-4000-8000-'
          || lpad((kind.id_base + call.n)::text, 12, '0'))::uuid,
       org."id", null, kind.provider, kind.model,
       measured.tokens / 5 * 4, measured.tokens / 5,
       kind.centre_cost + (call.n - kind.centre) * kind.cost_step,
       month_window.start_at
         + (utc.day_start - month_window.start_at)
           * (call.n::double precision / (kind.calls + 1)),
       kind.task_kind, measured.latency_ms
  from (values
         --  base  task kind     provider             model
         --                                  calls  centre  cost¢  step    p50ms  step   tokens  step
         (   0, 'analyze',    'anthropic',         'claude-sonnet-5',
             25,  13,   4.0000, 0.2500,  3100,  200,   50000,  2000),
         (  25, 'estimate',   'anthropic',         'claude-haiku-4-5',
             25,  13,   1.0000, 0.0500,  1200,   80,   14000,   500),
         (  50, 'plan',       'anthropic',         'claude-fable-5',
             15,   8,  31.0000, 3.0000,  9800,  900,  100000,  8000),
         (  65, 'implement',  'anthropic',         'claude-fable-5',
             15,   8,  87.0000, 9.0000, 41000, 3500,  260000, 20000),
         (  80, 'test-gen',   'copilot',           'gpt-5-codex',
             15,   8,  12.0000, 1.5000, 17400, 1800,  140000, 10000),
         (  95, 'review',     'anthropic',         'claude-fable-5',
             15,   8,  22.0000, 2.5000, 12600, 1200,  140000, 12000),
         ( 110, 'docs',       'ollama',            'qwen3-coder:32b',
             15,   8,   0.0000, 0.0000,  6300,  600,   40000,  3000),
         ( 125, 'commit-msg', 'openai_compatible', 'llama-4-maverick',
            245, 123,   0.0000, 0.0000,   800,    6,   80000,   500)
       ) as kind (id_base, task_kind, provider, model, calls, centre,
                  centre_cost, cost_step, centre_latency, latency_step,
                  centre_tokens, token_step)
  cross join lateral generate_series(1, kind.calls) as call (n)
  cross join lateral
       (select (kind.centre_tokens  + (call.n - kind.centre) * kind.token_step)::int,
               (kind.centre_latency + (call.n - kind.centre) * kind.latency_step)::int)
    as measured (tokens, latency_ms)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  cross join (select date_trunc('month', now() at time zone 'utc') at time zone 'utc',
                     date_trunc('day',   now() at time zone 'utc') at time zone 'utc')
          as utc (month_start, day_start)
  cross join lateral (select case
                              when utc.month_start < utc.day_start
                              then greatest(utc.month_start,
                                            utc.day_start - interval '13 days')
                              else utc.day_start - interval '1 day'
                            end)
          as month_window (start_at)
 where ${ouro_dev_seed}
on conflict do nothing;
