-- R__dev_seed_routing.sql — mockup 06's routing screen, as rows, in a development database
-- and nowhere else — and, since #582, the registry half of mockup 21 drawn over the same rows.
--
-- The fourth development seed, and it answers the fourth question. R__dev_seed.sql (#23) is
-- *who exists*, R__dev_seed_dashboard.sql (#68) is *what the loop has done*,
-- R__dev_seed_providers.sql (#221) is *what it is allowed to call*, and this is **how it
-- decides which one to call** — and, since CG.4 (#582), **what the registry says about the
-- same names**: the eight aliases' params and restrictions, what each costs, and the one
-- stored resolution mockup 21's chain card renders. All of it belongs to `acme-robotics`, the
-- workspace every mockup is drawn in.
--
-- docs/mockups/06-model-routing.html draws five surfaces and two numeric columns, and this
-- file is every one of them but the first:
--
--   | Surface                     | Rows                                                  |
--   |-----------------------------|-------------------------------------------------------|
--   | Provider health strip       | `provider_connections.health` — #221's, and its alone |
--   | Routing matrix (8 rows)     | `task_kinds` × `routes` × the first two `route_hops`  |
--   | Route inspector             | `implement-primary`'s three hops and its policies     |
--   | Escalation rules (3 active) | `escalation_rules`, sentences generated by V018       |
--   | Spend by provider · 30d     | `token_usage`, aggregated — nothing stored            |
--   | `$/run avg` and `p50`       | `token_usage.task_kind` and `.latency_ms` (V020)      |
--
-- Filed as issue #192 (Y.4). The schema it fills is V015/V017 (aliases), V016 (kinds,
-- routes, hops), V018 (rules) and V010 as extended by V020 (the usage the stats are
-- computed from). Read by Z.5 (#198), Z.6 (#199), AA.2 (#201), AA.5 (#204) and AA.7 (#206).
--
-- ---------------------------------------------------------------------------
-- Extended, not forked, by issue #582 (CG.4) — mockup 21 over the same rows.
-- ---------------------------------------------------------------------------
--
-- docs/mockups/21-model-registry.html is drawn over a **superset** of this file's rows: the
-- same aliases with their params and their prices, plus one unbound name and one stored
-- resolution. The roadmap's amendment to Y.4 (docs/ROADMAP_MOCKUP_21_MODEL_REGISTRY.md) puts
-- that superset *in this file* rather than beside it, because a second seed writing
-- `model_aliases` would give the routing page and the registry page a universe each to
-- disagree about. So three things below are #582's — the eighth alias and every `params`
-- document, the one `model_prices` override, and the run #482 `resolution_snapshots` row —
-- and mockup 21's surfaces read:
--
--   | Surface (mockup 21)          | Rows                                                  |
--   |------------------------------|-------------------------------------------------------|
--   | Allowed models (8 rows)      | `model_aliases`, incl. the unbound `gpt5-experiments` |
--   | Params chips                 | `model_aliases.params` / `.restrictions` — CH.2 derives|
--   | `$ per 1M in·out`            | `model_prices` — the bundled catalog + one override    |
--   | Health                       | `provider_connections.status` — #221's; CH.5 derives  |
--   | Used by                      | `alias_references` (V023) — computed, never stored    |
--   | Resolution chain (run #482)  | `resolution_snapshots` (V024) — one row               |
--
-- Nothing the registry *renders* is stored where it could be typed instead. No chip string,
-- no `degraded`, no `$15 · $75`, no `4 routes`: the chips are derived from `params` by CH.2
-- (#585), the health cell from the connection's status by CH.5 (#588), the price from the
-- catalog by CH.3 (#586), and the count from V023's view. tests/seed.test.sh asserts each of
-- those strings is absent from this file, and tests/seed.sql asserts what the derivations
-- have to work from.
--
-- ---------------------------------------------------------------------------
-- Decision M7, which is the whole reason this file is as long as it is.
-- ---------------------------------------------------------------------------
--
--   > `$/run`, p50 and spend are **computed** from `token_usage` + runs; no data → em-dash,
--   > never a fabricated number; local providers show `$0.00` only via real zero-price rows.
--
-- So `$0.87`, `41.0s`, `$412.80` and *"Local models served 31% of all tokens"* are **not**
-- seeded anywhere. There is no column on a route, an alias or a connection that any of them
-- could be written into, and this file writes none. What it seeds instead is the *usage*
-- those figures are aggregates of, arranged so the aggregation lands on the mockup.
--
-- That is a deliberately harder job than storing the answers, and it is the job because of
-- what storing them would cost: a `$/run` column filled by a seed leaves Z.5's aggregation
-- untested and M7's em-dash rule unverifiable. A number that was never computed cannot be
-- *absent* in the way the rule requires — the honest em-dash of a workspace with no data is
-- only observable if the populated workspace's figure was computed too.
--
-- **The arithmetic, in one table.** Each task kind is seeded a run of calls whose costs and
-- latencies are a symmetric arithmetic sequence around the mockup's figure — so the *mean*
-- of the costs is the `$/run avg` column exactly, and the *median* of the latencies is the
-- `p50 latency` column exactly, with no rounding anywhere:
--
--   | Task kind    | Calls | mean cost | `$/run avg` | median latency | `p50`  |
--   |--------------|------:|----------:|------------:|---------------:|-------:|
--   | `analyze`    |    25 |      4.00¢|       $0.04 |         3100ms |   3.1s |
--   | `estimate`   |    25 |      1.00¢|       $0.01 |         1200ms |   1.2s |
--   | `plan`       |    15 |     31.00¢|       $0.31 |         9800ms |   9.8s |
--   | `implement`  |    15 |     87.00¢|       $0.87 |        41000ms |  41.0s |
--   | `test-gen`   |    15 |     12.00¢|       $0.12 |        17400ms |  17.4s |
--   | `review`     |    15 |     22.00¢|       $0.22 |        12600ms |  12.6s |
--   | `docs`       |    15 |      0.00¢|       $0.00 |         6300ms |   6.3s |
--   | `commit-msg` |   245 |      0.00¢|       $0.00 |          800ms |   0.8s |
--
-- A symmetric sequence is what makes both exact at once. Offsets either side of the centre
-- cancel in a sum, so `avg(cost_cents)` is the centre; an odd number of calls puts one row
-- *at* the centre, so `percentile_cont(0.5)` is that row rather than an interpolation. The
-- spread is real variation — an `implement` call ranges 16.5s to 65.5s, and 24¢ to $1.50 —
-- which is what a median is worth having for.
--
-- ---------------------------------------------------------------------------
-- The four seeds share one ledger, and this one takes its spend out of #221's share.
-- ---------------------------------------------------------------------------
--
-- `token_usage` is one table and three of the four seeds write to it, so a row added here
-- moves a figure mockup 02 and mockup 07 already render. Two rules keep that from happening,
-- and both are asserted in tests/seed.sql:
--
--   1. **Nothing here lands on today.** Mockup 02's *Token spend · today* card is exactly
--      #68's twelve events; every row below is placed strictly before today's UTC midnight,
--      in the same window #221 uses and with the same first-of-the-month branch.
--
--   2. **The month meters do not move**, because #221 was reduced by exactly what this file
--      adds. Its header carries the arithmetic; the short form is that routed spend of
--      $22.25 (Anthropic) and $1.80 (Copilot) came out of that file's remainder rather than
--      on top of it, and 600 000 routed `docs` tokens came out of its Ollama share, so the
--      cards still read $412.80 / $64.10 / $76.00 and *2.1M tokens on-box*.
--
-- **What the 30-day card therefore reads, and where the mockup does not close.** Every row
-- any seed writes falls inside the trailing thirty days, so *Spend by provider · 30d* is the
-- calendar-month figure on every day of the month:
--
--   | Provider                | Seeded 30d | Mockup 06 | Mockup 07 (month) |
--   |-------------------------|-----------:|----------:|------------------:|
--   | Anthropic               |    $412.80 |   $412.80 |           $412.80 |
--   | GitHub Copilot          |     $76.00 |    $96.40 |            $76.00 |
--   | Cursor                  |     $64.10 |    $54.10 |            $64.10 |
--   | Local (vLLM + Ollama)   |      $0.00 |     $0.00 |             $0.00 |
--
-- The two disagreements are the mockups', not the seed's, and one of them is **not
-- reachable by any seed at all**: thirty days is a superset of month-to-date, so a 30-day
-- total can never be *less* than the month total inside it, and mockup 06 asks Cursor to be
-- $10.00 lower than mockup 07's card for the same rows. Copilot's $96.40 would need $20.40
-- dated before the month began — a window that is twenty-nine days wide on the 2nd and
-- **empty** on the 31st, which would make the card's figure depend on the date.
--
-- So this file seeds the reading both screens can hold at once, and states the discrepancy
-- here rather than leaving Z.5 (#198) to find it against a fixture that will not add up —
-- the same courtesy R__dev_seed_dashboard.sql pays where mockup 02's merge rate does not
-- close. Anthropic and the local `$0.00` land on the mockup exactly; Copilot and Cursor land
-- on mockup 07's, and #192's PR asks for the design to be amended to them.
--
-- ---------------------------------------------------------------------------
-- Zero-priced is not unpriced, and the difference is seeded in one workspace.
-- ---------------------------------------------------------------------------
--
-- `docs` and `commit-msg` route to local models, and their `$0.00` in the matrix — and the
-- local provider's `$0.00` on the spend card — is only honest if the calls were **priced,
-- and priced at nothing**. Their rows therefore carry `cost_cents = 0`, which is a recorded
-- fact about a call that cost nothing.
--
-- #68's and #221's Ollama rows carry `null` instead, which says the other thing: *nobody
-- priced this*. Both states now exist in `acme-robotics`, which is what makes DASH-J.4's
-- (#92) rule testable — a re-pricing pass must fill the nulls and leave the zeros alone, and
-- a stats service must render `$0.00` for one and `unpriced` for the other. Seeding only one
-- of the two would have left the distinction as a sentence in a header.
--
-- **The local token share is the same rule counted rather than summed.** *"Local models
-- served 31% of all tokens"* is `tokens on the two local kinds / all tokens` over the same
-- thirty days, and it lands on exactly 31% because the pieces were chosen to:
--
--   |                       | Cloud tokens | Local tokens |
--   |-----------------------|-------------:|-------------:|
--   | #68 — today           |    3 700 000 |      500 000 |
--   | #221 — earlier        |   33 400 000 |    1 000 000 |
--   | here — routed calls   |   11 200 000 |   20 200 000 |
--   | **Total**             | **48 300 000** | **21 700 000** |
--
-- 21 700 000 of 70 000 000 is 31.0%, with no rounding. The local half is large because that
-- is what the claim means: a workstation that answers every commit message and every docs
-- pass serves a third of the tokens and none of the bill.
--
-- ---------------------------------------------------------------------------
-- No `runs` row is written here, and that is decision M7 read carefully.
-- ---------------------------------------------------------------------------
--
-- A `runs` row is a **loop** — one issue, from *Implementing* to *Merged* — and mockup 02's
-- *Loops live*, *PRs merged · 7d* and *Avg. cycle time* are counts and averages over the
-- fifty-three #68 seeds. A routing call is a *step inside* a loop, and there are 370 of them
-- below; writing one run per call would change every figure on the dashboard.
--
-- V020 is what makes that unnecessary: `task_kind` and `latency_ms` live on the ledger row,
-- which is already one row per call, so the matrix's two columns are aggregates over rows
-- this file writes and the dashboard's are aggregates over rows #68 wrote. `run_id` is left
-- null throughout — these calls belong to a *kind of work*, and inventing a mapping from 370
-- synthetic calls onto 53 loops would be a fixture nothing renders.
--
-- ---------------------------------------------------------------------------
-- Ids, and the three properties every seed here has.
-- ---------------------------------------------------------------------------
--
-- Eight prefixes, on the convention R__dev_seed.sql set — an id beginning `5eed` came from a
-- seed, and the two hex digits after it say which table:
--
--   | Rows                        | Id                                                  |
--   |-----------------------------|-----------------------------------------------------|
--   | `model_aliases` (8)         | `5eed000f-0000-4000-8000-` + ordinal 1–8            |
--   | `task_kinds` (8)            | `5eed0010-0000-4000-8000-` + matrix position 1–8    |
--   | `routes` (8)                | `5eed0011-0000-4000-8000-` + its kind's position    |
--   | `route_hops` (17)           | `5eed0012-0000-4000-8000-` + ordinal 1–17           |
--   | `escalation_rules` (3)      | `5eed0013-0000-4000-8000-` + card position 1–3      |
--   | `token_usage` (370)         | `5eed0014-0000-4000-8000-` + ordinal 1–370          |
--   | `model_prices` (1)          | `5eed0016-0000-4000-8000-` + 1                      |
--   | `resolution_snapshots` (1)  | `5eed0017-0000-4000-8000-` + 1                      |
--
-- (`5eed0015` is R__dev_seed_audit.sql's, which sorts before this file and took it first.)
--
-- The usage ids are computed from a per-kind base and the call's number rather than written
-- out, for the reason #68 computes its seventy-seven: a list of 370 literals is a list nobody
-- proof-reads. They are as deterministic as literals are — the same file yields the same
-- uuid on every machine and every pass — which is the property the convention is for.
-- `gen_random_uuid()` appears nowhere, and tests/seed.test.sh asserts it.
--
-- It **cannot run in production** (every statement ends `and ${ouro_dev_seed}`, which is
-- `false` in flyway.toml), it is **idempotent** (every id is derived from literals and every
-- statement ends `on conflict do nothing`), and it **never fails on a database somebody has
-- edited** (children find their parents by natural key — the workspace by slug, a connection
-- by its kind and name, a kind by its name, an alias by its alias). Three statements name
-- their arbiter as `on conflict (id)`: `task_kinds`, `route_hops` and `escalation_rules` all
-- carry a **deferrable** unique key, and PostgreSQL refuses a targetless `on conflict` on
-- such a table outright — the same accommodation #68 makes for `queue_items`.
--
-- **The personal workspace is deliberately empty.** `kensuenobu` gets no alias, no task kind,
-- no route and no usage row, exactly as it gets no run and no provider — which is what makes
-- it the fixture AA.6 (#205) renders *"set up your first route"* against, and the one M7's
-- em-dashes can be observed in: a workspace with no usage has no `$/run` to average and no
-- latency to take a median of, and both must render `—` rather than `$0.00` and `0.0s`. It
-- gets no price override and no resolution snapshot either, so it is also the empty registry
-- CI.6 (#596) renders its guidance against.
--
-- ---------------------------------------------------------------------------
-- The eight aliases — the only place a raw model string is allowed to live.
--
-- Decision M1: routes name aliases, aliases name models, and `model_aliases.model_id` is the
-- one column in this schema where `claude-fable-5` may appear. Every hop below therefore
-- points at one of these rows, and swapping `coder-max` onto another model stays one edit of
-- one row.
--
-- Six are the matrix's. The seventh is `second-opinion`, which no route's chain contains and
-- the *security label* escalation rule names — Y.3 (#191) put that rule in the schema, so the
-- alias it adds a vote from has to exist here or the rule cannot be written at all. The
-- eighth is `gpt5-experiments`, mockup 21's **unbound** row (CG.4, #582; V019, decision R2):
-- a name created ahead of its key, bound to no connection, naming `gpt-5.2-preview`, and
-- `enabled = false` — which V019 requires of an unbound row rather than defaults, so the seed
-- says it. It is the registry's `✗ no key — connect a provider` fixture, and nothing routes
-- through it: its `0 routes` is a left join over `alias_references` that finds nothing.
--
-- **`params` and `restrictions` are mockup 21's chips, as structure** (V019, decision R3).
-- The registry draws `(max thinking)(400k budget)` beside `coder-max`, `(std thinking)`
-- beside `coder-std`, `(temp 0)(8k out)` beside `sizer`, `(ctx 32k)` beside `local-docs`,
-- `(batch ok)` beside `local-free` and `(review vote only)` beside `second-opinion`; none of
-- those strings is in this file. What is here is `{"thinking": "max", "token_budget":
-- 400000}` and its siblings, and CH.2 (#585) derives the chips — so the registry's parity
-- test passes only if the derivation works, which is the point of seeding structure rather
-- than text. `8192` and `32768` are stored as the powers of two the chips abbreviate, and
-- `400000` as the round thousand it is; CH.2 prints each in the unit it is a whole multiple
-- of. `coder-fallback` and `gpt5-experiments` carry nothing, which is the `—` cell: a
-- fixed-catalog model with nothing to tune, and a name with no provider to tune it for.
--
-- **`coder-max` carrying `thinking: max` does not make the effort ≥ L rule a no-op**, though
-- an earlier version of this header said it would. The rule's `params` are *policy* — Z.1
-- (#194) merges them over whatever the alias carries at resolution time, so the rule pins max
-- thinking for large work even after somebody edits the alias down to `std` — while the
-- alias's `params` are the registry's claim about how this name is called by default. In the
-- seeded workspace the two agree, and the merge is observably a merge rather than a swap: the
-- rule's document names `thinking` alone, and the resolved params still carry the alias's
-- `token_budget`.
--
-- Each bound alias finds its connection by natural key — the kind and display name #221
-- seeded — so no id from that file is repeated here. The unbound one has no connection to
-- find, and the `left join` plus the last `and` keep the two cases apart: a bound row whose
-- connection somebody has deleted is *skipped* rather than inserted as unbound, because V019
-- would refuse it enabled and take the whole migration down with it.
-- ---------------------------------------------------------------------------
insert into ouroboros.model_aliases
    (id, organization_id, alias, provider_connection_id, model_id, params,
     enabled, restrictions, updated_by)
select ('5eed000f-0000-4000-8000-' || lpad(seed.n::text, 12, '0'))::uuid,
       org."id", seed.alias, conn.id, seed.model_id, seed.params::jsonb,
       seed.enabled, seed.restrictions::jsonb, person."id"
  from (values
         (1, 'coder-max',        'anthropic',         'Anthropic Claude',
          'claude-fable-5',   '{"thinking": "max", "token_budget": 400000}', '{}', true),
         (2, 'coder-std',        'anthropic',         'Anthropic Claude',
          'claude-sonnet-5',  '{"thinking": "std"}',                         '{}', true),
         (3, 'sizer',            'anthropic',         'Anthropic Claude',
          'claude-haiku-4-5', '{"temperature": 0, "max_output": 8192}',      '{}', true),
         (4, 'coder-fallback',   'copilot',           'GitHub Copilot',
          'gpt-5-codex',      '{}',                                          '{}', true),
         (5, 'local-docs',       'ollama',            'Ollama · workstation',
          'qwen3-coder:32b',  '{"context_clamp": 32768}',                    '{}', true),
         (6, 'local-free',       'openai_compatible', 'OpenAI-compatible · local vLLM',
          'llama-4-maverick', '{}',                          '{"batch_ok": true}', true),
         (7, 'second-opinion',   'cursor',            'Cursor',
          'composer-2',       '{}',                   '{"review_vote_only": true}', true),
         (8, 'gpt5-experiments', null,                null,
          'gpt-5.2-preview',  '{}',                                          '{}', false)
       ) as seed (n, alias, kind, display_name, model_id, params, restrictions, enabled)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  join ouroboros."user" person on person."email" = 'ken@acme-robotics.dev'
  left join ouroboros.provider_connections conn
    on conn.organization_id = org."id"
   and conn.kind = seed.kind
   and conn.display_name = seed.display_name
 where ${ouro_dev_seed}
   and (seed.kind is null) = (conn.id is null)
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- The eight task kinds — the matrix's rows, in the matrix's order.
--
-- `name` is the mono label the row prints and `description` is the grey line under it,
-- verbatim. `sort_order` is the order the mockup draws them in, which is the loop's own
-- order of operations: read the issue, size it, plan it, write it, test it, review it,
-- document it, commit it.
--
-- Stored rather than derived because it is a *workspace's* list: a team that never generates
-- tests deletes that row, and a team with a `triage` step adds one. Nothing here is a
-- vocabulary — V016 constrains the shape of a name, never the set of them.
-- ---------------------------------------------------------------------------
insert into ouroboros.task_kinds (id, organization_id, name, description, sort_order)
select ('5eed0010-0000-4000-8000-' || lpad(seed.sort_order::text, 12, '0'))::uuid,
       org."id", seed.name, seed.description, seed.sort_order
  from (values
         (1, 'analyze',    'Read the issue, map the affected code paths'),
         (2, 'estimate',   'Size effort XS–XL before queueing'),
         (3, 'plan',       'Decompose into steps, pick a workflow'),
         (4, 'implement',  'Write the change, run tests, iterate to green'),
         (5, 'test-gen',   'Generate unit and regression tests for the diff'),
         (6, 'review',     'Self-review the PR against the acceptance criteria'),
         (7, 'docs',       'Update READMEs, changelogs, operator manual'),
         (8, 'commit-msg', 'Conventional-commit message from the staged diff')
       ) as seed (sort_order, name, description)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
 where ${ouro_dev_seed}
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The eight routes — one per kind, and the inspector's three policies.
--
-- `tag` is the name the matrix prints as a pill and the inspector's title —
-- `implement-primary`. V016 makes it unique per workspace, so it is what a URL and an
-- explanation can name a route by without carrying a uuid.
--
-- **Only `implement-primary` carries a cost cap**, because it is the only route the mockup
-- opens: its inspector reads *Max cost per run* `$2.50`, which is `max_cost_cents_per_run =
-- 250`. The other seven are null — *no cap configured* — rather than 250 repeated eight
-- times, because a policy nobody set is not a policy, and a seed that quietly applies one
-- everywhere would make the inspector's field look like a display of a default.
--
-- `allow_local_fallback` is on everywhere, which is the mockup's switch and V016's default;
-- `floor_hop_index` is null everywhere, which is *"Fail run instead of degrading below
-- fallback 2"* switched **off**. Null rather than a number is what off means here: a floor is
-- a hop index, and there is no index that means "no floor".
--
-- `updated_by` is Ken, the person who owns the workspace — these are routes somebody saved,
-- which is what the *Save routes* button writes.
-- ---------------------------------------------------------------------------
insert into ouroboros.routes
    (id, organization_id, task_kind_id, tag, allow_local_fallback,
     floor_hop_index, max_cost_cents_per_run, updated_by)
select ('5eed0011-0000-4000-8000-' || lpad(seed.sort_order::text, 12, '0'))::uuid,
       org."id", kind.id, seed.tag, true, null, seed.max_cost_cents, person."id"
  from (values
         (1, 'analyze',    'analyze-primary',    null),
         (2, 'estimate',   'estimate-primary',   null),
         (3, 'plan',       'plan-primary',       null),
         (4, 'implement',  'implement-primary',  250),
         (5, 'test-gen',   'testgen-primary',    null),
         (6, 'review',     'review-primary',     null),
         (7, 'docs',       'docs-primary',       null),
         (8, 'commit-msg', 'commitmsg-primary',  null)
       ) as seed (sort_order, kind_name, tag, max_cost_cents)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  join ouroboros.task_kinds kind
    on kind.organization_id = org."id" and kind.name = seed.kind_name
  join ouroboros."user" person on person."email" = 'ken@acme-robotics.dev'
 where ${ouro_dev_seed}
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- The seventeen hops — the chains, in order.
--
-- The matrix shows a route's first two hops as its *Primary model* and *Fallback* columns;
-- the inspector shows the whole chain, which is why `implement-primary` has three and the
-- other seven have two. `position` is dense from 1 within each route, which V016 makes a
-- correctness rule rather than a convention — `floor_hop_index` is a statement about a hop
-- *number*, and a chain numbered 1, 2, 5 makes *"fail instead of degrading below fallback
-- 2"* mean nothing.
--
-- **`note` is written where the mockup writes prose and left null where it composes one.**
-- The inspector's hop 2 and hop 3 print *"Fallback on 5xx / timeouts"* and *"Offline mode —
-- keeps the loop turning without a network"*, which are an operator's sentences and are
-- stored. Hop 1 prints *"Primary · API key valid, 42ms to us-east"*, which is not: *Primary*
-- is position 1, *API key valid* is the connection's status, and `42ms` is
-- `health.latency_ms` measured minutes ago. Storing that sentence would freeze a latency
-- into a note and make the chip and the hop disagree the first time a check ran.
--
-- The other seven routes have no notes at all, which is the ordinary state — V016 made the
-- column nullable for it, and a seed that invented a sentence per hop would be putting words
-- in an operator's mouth.
-- ---------------------------------------------------------------------------
insert into ouroboros.route_hops
    (id, organization_id, route_id, position, model_alias_id, note)
select ('5eed0012-0000-4000-8000-' || lpad(seed.n::text, 12, '0'))::uuid,
       org."id", route.id, seed.position, alias.id, seed.note
  from (values
         ( 1, 'analyze-primary',   1, 'coder-std',      null),
         ( 2, 'analyze-primary',   2, 'local-docs',     null),
         ( 3, 'estimate-primary',  1, 'sizer',          null),
         ( 4, 'estimate-primary',  2, 'local-free',     null),
         ( 5, 'plan-primary',      1, 'coder-max',      null),
         ( 6, 'plan-primary',      2, 'coder-std',      null),
         ( 7, 'implement-primary', 1, 'coder-max',      null),
         ( 8, 'implement-primary', 2, 'coder-fallback', 'Fallback on 5xx / timeouts'),
         ( 9, 'implement-primary', 3, 'local-docs',
          'Offline mode — keeps the loop turning without a network'),
         (10, 'testgen-primary',   1, 'coder-fallback', null),
         (11, 'testgen-primary',   2, 'coder-std',      null),
         (12, 'review-primary',    1, 'coder-max',      null),
         (13, 'review-primary',    2, 'coder-std',      null),
         (14, 'docs-primary',      1, 'local-docs',     null),
         (15, 'docs-primary',      2, 'sizer',          null),
         (16, 'commitmsg-primary', 1, 'local-free',     null),
         (17, 'commitmsg-primary', 2, 'sizer',          null)
       ) as seed (n, tag, position, alias, note)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  join ouroboros.routes route
    on route.organization_id = org."id" and route.tag = seed.tag
  join ouroboros.model_aliases alias
    on alias.organization_id = org."id" and alias.alias = seed.alias
 where ${ouro_dev_seed}
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The three escalation rules — `3 active`.
--
-- Structure, never sentences. `display` is a **stored generated column** (V018): PostgreSQL
-- derives the card's line from `"when"` and `"then"` and refuses a hand-written one, so the
-- three rows below produce the mockup's three sentences character for character without this
-- file spelling any of them:
--
--   `{"effort_gte": "l"}` + `{"use_alias": {…, "params": {"thinking": "max"}}}`
--     ─▶ effort ≥ L → implement uses coder-max (max thinking)
--   `{"label": "security"}` + `{"add_vote": {…}}`
--     ─▶ security label → review adds second-opinion vote
--   `{"diff_kind": "docs_only"}` + `{"route_local": {}}`
--     ─▶ docs-only diff → everything routes local
--
-- The mockup's *"(max thinking)"* is `params` on the rule rather than prose, which is what
-- lets Z.1 (#194) merge it over the alias's params instead of parsing a phrase.
--
-- `escalation_rule_targets_exist()` is a **deferred** constraint trigger over the task kind
-- and alias these documents name — neither is reachable by a foreign key, because both live
-- inside jsonb. Deferral is what lets this statement run in any order relative to the two
-- above; it is checked at commit, when all three tables are populated.
--
-- **One mockup inconsistency worth knowing about.** The matrix draws the first rule's summary
-- on the `plan` row and the second's on `review`, while the rules card says the first rule
-- modifies `implement`. Y.3 (#191) settled that in the schema's favour — its `then` names
-- `implement`, and tests/constraints.sql asserts the sentence — so the matrix's *Escalation*
-- column, computed from these rows, shows the rule on `implement` and an em-dash on `plan`.
-- That is the structure the card and the matrix now share; the mockup drew them separately.
-- ---------------------------------------------------------------------------
insert into ouroboros.escalation_rules
    (id, organization_id, enabled, sort_order, "when", "then")
select ('5eed0013-0000-4000-8000-' || lpad(seed.sort_order::text, 12, '0'))::uuid,
       org."id", true, seed.sort_order, seed.rule_when::jsonb, seed.rule_then::jsonb
  from (values
         (1, '{"effort_gte": "l"}',
             '{"use_alias": {"task_kind": "implement", "alias": "coder-max",'
             || ' "params": {"thinking": "max"}}}'),
         (2, '{"label": "security"}',
             '{"add_vote": {"task_kind": "review", "alias": "second-opinion"}}'),
         (3, '{"diff_kind": "docs_only"}',
             '{"route_local": {}}')
       ) as seed (sort_order, rule_when, rule_then)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
 where ${ouro_dev_seed}
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The 370 routed calls — everything the matrix's two numeric columns are made of.
--
-- One row per model call, which is the grain V010 chose and the grain both figures are
-- about. `task_kind` says which matrix row a call belongs to and `latency_ms` how long it
-- took (V020); `provider` and `model` are the connection and model its route's **primary**
-- hop resolves to, which is what a call that succeeded on its first hop records.
--
-- **The three sequences.** For a kind with `calls` rows, call `n` records
--
--   cost_cents = centre_cost    + (n − centre) × cost_step
--   latency_ms = centre_latency + (n − centre) × latency_step
--   tokens     = centre_tokens  + (n − centre) × token_step
--
-- with `centre = (calls + 1) / 2`. The offsets are symmetric, so each column's *mean* is its
-- centre — which makes `avg(cost_cents)` the `$/run avg` column exactly — and `calls` is odd,
-- so one row sits **at** the centre and `percentile_cont(0.5)` returns it rather than an
-- interpolation between two neighbours. Token totals are `calls × centre_tokens` for the same
-- reason, which is what makes the 31% share above land on a whole number.
--
-- Every centre is a multiple of five and every step divides it, so `tokens_in` and
-- `tokens_out` — four fifths and one fifth, as both earlier seeds split them — add back up to
-- the total with nothing lost to integer division.
--
-- **`cost_cents = 0` on the two local kinds, and it is not a null.** See the header: zero is
-- a price that was recorded, null is a price nobody recorded, and this workspace now holds
-- both so the difference is testable rather than asserted.
--
-- **The window** is #221's, for the reason its header gives: `occurred_at` is
-- `start + (today 00:00 − start) × n/(calls + 1)`, so every call lands strictly inside
-- `[start, today 00:00 UTC)` and none on either edge. `start` is the later of the month's
-- first instant and thirteen days ago — except on the first of a month, when *earlier this
-- month* is an empty range and the window is yesterday instead. On that one day the month
-- meters read the day's spend alone, exactly as they do without this file; the 30-day card
-- and the per-kind statistics are unaffected, because a window of thirteen days and a window
-- of one are both inside thirty.
-- ---------------------------------------------------------------------------
insert into ouroboros.token_usage
    (id, organization_id, run_id, provider, model, tokens_in, tokens_out,
     cost_cents, occurred_at, task_kind, latency_ms)
select ('5eed0014-0000-4000-8000-'
          || lpad((kind.id_base + call.n)::text, 12, '0'))::uuid,
       org."id", null, kind.provider, kind.model,
       measured.tokens / 5 * 4, measured.tokens / 5,
       kind.centre_cost + (call.n - kind.centre) * kind.cost_step,
       month_window.start_at
         + (utc.day_start - month_window.start_at)
           * (call.n::double precision / (kind.calls + 1)),
       kind.task_kind, measured.latency_ms
  from (values
         --  base  task kind     provider             model
         --                                  calls  centre  cost¢  step    p50ms  step   tokens  step
         (   0, 'analyze',    'anthropic',         'claude-sonnet-5',
             25,  13,   4.0000, 0.2500,  3100,  200,   50000,  2000),
         (  25, 'estimate',   'anthropic',         'claude-haiku-4-5',
             25,  13,   1.0000, 0.0500,  1200,   80,   14000,   500),
         (  50, 'plan',       'anthropic',         'claude-fable-5',
             15,   8,  31.0000, 3.0000,  9800,  900,  100000,  8000),
         (  65, 'implement',  'anthropic',         'claude-fable-5',
             15,   8,  87.0000, 9.0000, 41000, 3500,  260000, 20000),
         (  80, 'test-gen',   'copilot',           'gpt-5-codex',
             15,   8,  12.0000, 1.5000, 17400, 1800,  140000, 10000),
         (  95, 'review',     'anthropic',         'claude-fable-5',
             15,   8,  22.0000, 2.5000, 12600, 1200,  140000, 12000),
         ( 110, 'docs',       'ollama',            'qwen3-coder:32b',
             15,   8,   0.0000, 0.0000,  6300,  600,   40000,  3000),
         ( 125, 'commit-msg', 'openai_compatible', 'llama-4-maverick',
            245, 123,   0.0000, 0.0000,   800,    6,   80000,   500)
       ) as kind (id_base, task_kind, provider, model, calls, centre,
                  centre_cost, cost_step, centre_latency, latency_step,
                  centre_tokens, token_step)
  cross join lateral generate_series(1, kind.calls) as call (n)
  cross join lateral
       (select (kind.centre_tokens  + (call.n - kind.centre) * kind.token_step)::int,
               (kind.centre_latency + (call.n - kind.centre) * kind.latency_step)::int)
    as measured (tokens, latency_ms)
  join ouroboros.organization org on org."slug" = 'acme-robotics'
  cross join (select date_trunc('month', now() at time zone 'utc') at time zone 'utc',
                     date_trunc('day',   now() at time zone 'utc') at time zone 'utc')
          as utc (month_start, day_start)
  cross join lateral (select case
                              when utc.month_start < utc.day_start
                              then greatest(utc.month_start,
                                            utc.day_start - interval '13 days')
                              else utc.day_start - interval '1 day'
                            end)
          as month_window (start_at)
 where ${ouro_dev_seed}
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- The one price override — `llama-4-maverick` is free *here*, not everywhere (#582).
--
-- Mockup 21's `$ per 1M in·out` column is `model_prices` (V012) read through
-- `ouroboros.model_price()`, and seven of its eight cells come out of the **bundled** catalog
-- without this file's help: the Anthropic trio are token rows, `copilot/*` is `seat`,
-- `cursor/*` is `usage` and `ollama/*` is `free`. The eighth priced cell is the one the
-- catalog deliberately does not carry. `openai_compatible` fronts a self-hosted vLLM *and*
-- `api.openai.com`, so a bundled `free` row for that kind would price every uncovered OpenAI
-- model at `$0` — and local-ness is a property of a **connection**, not of an adapter kind.
-- V012's header argues that; this row is its consequence: an `override` scoped to
-- `acme-robotics`, for the model `local-free` binds on the vLLM connection, at no charge,
-- because the A100s in the capability note are already paid for.
--
-- Both halves of the match are read from the rows they price rather than typed, so the
-- override cannot drift from the alias it is for. `gpt-5.2-preview` gets **no row**, in the
-- catalog or here: the registry's `—` is *unpriced*, and R4 forbids inventing the number.
--
-- Three of the mockup's figures do not match the catalog, and the catalog wins: it prices
-- `claude-fable-5` at `$10 · $50` and `claude-sonnet-5` at `$2 · $10` where the drawing reads
-- `$15 · $75` and `$3 · $15`. CG.2's (#580) shipped note settled that — the vendored snapshot
-- is the truth source and a figure in a design drawing is a layout — and an override here
-- that made the column read the drawing would be a fabricated price, which is exactly what
-- the honesty rules M7/P8 forbid. #582's PR asks for the design to be amended instead.
-- ---------------------------------------------------------------------------
insert into ouroboros.model_prices
    (id, organization_id, match_provider_kind, match_model, billing_mode,
     input_cents_per_1m, output_cents_per_1m, source, catalog_version, meta)
select '5eed0016-0000-4000-8000-000000000001'::uuid,
       org."id", conn.kind, alias.model_id, 'free', null, null, 'override', null,
       jsonb_build_object(
         'note', 'served by the workspace''s own vLLM — the hardware is already paid for')
  from ouroboros.organization org
  join ouroboros.provider_connections conn
    on conn.organization_id = org."id"
   and conn.kind = 'openai_compatible'
   and conn.display_name = 'OpenAI-compatible · local vLLM'
  join ouroboros.model_aliases alias
    on alias.organization_id = org."id"
   and alias.provider_connection_id = conn.id
   and alias.alias = 'local-free'
 where org."slug" = 'acme-robotics'
   and ${ouro_dev_seed}
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Run #482's resolution — the chain card, as a stored row (#582, decision R9).
--
-- Mockup 21's RESOLUTION CHAIN card reads
--
--   route.task("implement") → route implement-primary → alias coder-max
--     → provider Anthropic (key …Xq4A) → model claude-fable-5    ● resolved · 42ms
--
-- under the tag `run #482`, and its caption promises that every hop is inspectable in the run
-- console. A card composed at render time from today's rows could not keep that promise —
-- see V024's header — so the card renders `resolution_snapshots`, and until AF.2 (#235)
-- writes one at execution time this is the one it renders: a fixture, in the executor's own
-- shape, for the run the dashboard seed already has.
--
-- **Almost nothing in it is typed.** The run is #68's `#482` — *Fix flaky CAN-bus telemetry
-- test*, `claude-fable-5`, at its *Implementing* stage — found by issue number. The task kind,
-- the route and the chain are this file's own `implement-primary` rows, walked hop by hop the
-- way Z.1 (#194) walks them: each hop copies its alias, model and params from `model_aliases`
-- and its provider's kind, name, status and measured latency from `provider_connections` —
-- the health snapshot *as it was*, which is what a snapshot is for — and decides `kept` or
-- `dropped` by the same rule `resolve()` applies to a status, with the sentence Z.1 would
-- have written. So the stored chain is three hops rather than the card's one: `coder-max`
-- kept and tried (`Primary · healthy · 42ms`), `coder-fallback` **dropped** because Copilot's
-- connection is in `error` (`Fallback 1 dropped — GitHub Copilot is unreachable (elevated
-- latency).`), and `local-docs` kept in reserve. The card draws the hop that resolved; the
-- run console can draw all three, which is the caption's promise.
--
-- Two values are the fixture's own. `42` is the resolution's duration and the one hop's, and
-- it is stored because a snapshot *is* the record of a measurement — the same `42` #221
-- stored as the Anthropic connection's measured latency, which is where the card's inspector
-- line gets it too. `Xq4A` is the masked tail of the key the hop resolved with: the
-- connection's credential is a sealed envelope (V015, AD.1), so its suffix is not derivable
-- from any row, and the snapshot carries it the way the executor will — copied at the moment
-- of resolution, four characters, never the key. It is the only credential-adjacent literal
-- in this file, and tests/seed.test.sh counts it.
--
-- `rules` is empty: the three seeded rules were evaluated for #482 and none matched — no
-- effort ≥ L on a *standard-fix*, no security label, not a docs-only diff — and an empty
-- list is what a run nothing modified stores. `resolved_at` is eight minutes into a run the
-- dashboard seed started 12m 40s ago, which is inside its *Implementing* stage and moves with
-- `now()` exactly as the run does.
-- ---------------------------------------------------------------------------
insert into ouroboros.resolution_snapshots
    (id, organization_id, run_id, shape_version, task_kind, route_tag, outcome,
     duration_ms, chain, rules, resolved_at)
select '5eed0017-0000-4000-8000-000000000001'::uuid,
       org."id", run.id, 1, kind.name, route.tag, 'resolved', 42,
       (select jsonb_agg(jsonb_build_object(
                 'index',       hop.position,
                 'position',    hop.position,
                 'alias',       alias.alias,
                 'model_id',    alias.model_id,
                 'params',      alias.params,
                 'provider',    jsonb_build_object(
                                  'kind',         conn.kind,
                                  'display_name', conn.display_name,
                                  'key_suffix',   case when hop.position = 1 then 'Xq4A' end,
                                  'status',       conn.status,
                                  'latency_ms',   conn.health -> 'latency_ms',
                                  'detail',       conn.health -> 'detail'),
                 'note',        hop.note,
                 'decision',    seen.decision,
                 'code',        seen.code,
                 'explanation', seen.explanation,
                 'duration_ms', case when hop.position = 1 then 42 end)
               order by hop.position)
          from ouroboros.route_hops hop
          join ouroboros.model_aliases alias
            on alias.id = hop.model_alias_id
          join ouroboros.provider_connections conn
            on conn.id = alias.provider_connection_id
          cross join lateral (
            select case when hop.position <= 1 then 'Primary'
                        else 'Fallback ' || (hop.position - 1)::text
                   end as role
          ) as hop_role
          cross join lateral (
            select case conn.status
                     when 'active'  then 'kept'
                     when 'unknown' then 'kept'
                     else 'dropped'
                   end as decision,
                   case conn.status
                     when 'active'  then 'provider_healthy'
                     when 'unknown' then 'provider_unknown'
                     when 'paused'  then 'provider_paused'
                     else 'provider_error'
                   end as code,
                   case conn.status
                     when 'active' then
                       hop_role.role || ' · '
                         || concat_ws(' · ', 'healthy',
                                      case when conn.health ? 'latency_ms'
                                           then (conn.health ->> 'latency_ms') || 'ms' end,
                                      conn.health ->> 'detail')
                     when 'unknown' then
                       hop_role.role || ' · '
                         || concat_ws(' · ', 'not checked yet', conn.health ->> 'detail')
                     when 'paused' then
                       hop_role.role || ' dropped — ' || conn.display_name
                         || ' is paused by an operator'
                         || coalesce(' (' || (conn.health ->> 'detail') || ')', '') || '.'
                     else
                       hop_role.role || ' dropped — ' || conn.display_name
                         || ' is unreachable'
                         || coalesce(' (' || (conn.health ->> 'detail') || ')', '') || '.'
                   end as explanation
          ) as seen
         where hop.route_id = route.id),
       '[]'::jsonb,
       run.started_at + interval '8 minutes'
  from ouroboros.organization org
  join ouroboros.runs run
    on run.organization_id = org."id" and run.issue_number = 482
  join ouroboros.task_kinds kind
    on kind.organization_id = org."id" and kind.name = 'implement'
  join ouroboros.routes route
    on route.organization_id = org."id" and route.task_kind_id = kind.id
 where org."slug" = 'acme-robotics'
   and ${ouro_dev_seed}
on conflict do nothing;
