-- R__model_price_catalog.sql — the bundled model price catalog, as rows.
--
-- **Generated. Do not edit.** Re-render it from the vendored extract with
--
--   ouroboros-db/scripts/price-catalog.mjs --write
--
-- and refresh that extract from upstream — the only step that touches a network, and one
-- nothing at migration time performs — with
--
--   ouroboros-db/scripts/price-catalog.mjs --vendor --commit <sha>
--
-- ci/db runs `--check`, so an edit here fails the pull request that made it.
--
-- ---------------------------------------------------------------------------
-- **Provenance.** Every row below is stamped `catalog_version = '2026-08-15+litellm.70d51a1'`
-- and traces to one of two places:
--
--   * 126 of them to **BerriAI/litellm/model_prices_and_context_window.json**, pinned at commit
--     70d51a196f0191a3768d6b1ff37adae0642f0bb3
--     (committed 2026-08-15T01:16:59Z), licensed MIT — see catalog/LICENSE.litellm for the
--     copy that came with it. The vendored extract is catalog/litellm-model-prices.json;
--     it is a pruned subset of that file and nothing else, so it can be diffed against
--     upstream directly. 3039 upstream entries were pruned to those 126: the
--     providers this product can reach (anthropic → anthropic, openai → openai_compatible), the
--     modes it routes work to (chat, responses), and only entries carrying a
--     positive cost in both directions.
--
--   * 3 of them — copilot (seat), cursor (usage), ollama (free) — to this
--     repository, stamped `meta.catalog_source = 'ouroboros'`. They are the kinds whose
--     billing is not per-token at all, for which upstream publishes no rate because there
--     is none to publish.
--
-- **The transform**, which is scripts/price-catalog.mjs and is documented in its header:
-- upstream's cost per token becomes cents per one million tokens (× 10^8) at the column's
-- four decimal places; `max_input_tokens`, `max_output_tokens` and the capability flags
-- are carried into `meta` for CH.2 (#585); an entry whose cost is missing, zero, or
-- rounds to zero is refused rather than imported as free.
--
-- **Repeatable**, so Flyway re-applies it whenever this file changes — which is whenever
-- a new snapshot is rendered — and skips it otherwise. What it calls is idempotent either
-- way: see ouroboros.import_model_price_catalog() in V012__model_prices.sql for what it
-- guarantees, including that no organization's override is reachable from here.
--
-- Filed as issue #580 (CG.2).

select ouroboros.import_model_price_catalog(
  '2026-08-15+litellm.70d51a1',
  '2026-08-15T01:16:59Z'::timestamptz,
  $catalog$[
    {"match_provider_kind":"copilot","match_model":"*","billing_mode":"seat","meta":{"catalog_source":"ouroboros","note":"GitHub Copilot is billed per seat and per premium request, not per token — upstream publishes no rate for it, because there is none to publish."}},
    {"match_provider_kind":"cursor","match_model":"*","billing_mode":"usage","meta":{"catalog_source":"ouroboros","note":"Cursor meters usage on terms this catalog cannot express as an input and an output rate."}},
    {"match_provider_kind":"ollama","match_model":"*","billing_mode":"free","meta":{"catalog_source":"ouroboros","note":"The Ollama adapter talks to a local daemon, so every model reached through it runs on hardware the workspace already pays for. Free by kind, not by model."}},
    {"match_provider_kind":"anthropic","match_model":"claude-3-7-sonnet-20250219","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"claude-3-7-sonnet-20250219","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"deprecation_date":"2026-02-19","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-3-haiku-20240307","billing_mode":"token","input_cents_per_1m":25,"output_cents_per_1m":125,"meta":{"catalog_source":"litellm","upstream_key":"claude-3-haiku-20240307","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":4096,"deprecation_date":"2026-04-20","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-3-opus-20240229","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":7500,"meta":{"catalog_source":"litellm","upstream_key":"claude-3-opus-20240229","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":4096,"deprecation_date":"2026-01-05","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-4-opus-20250514","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":7500,"meta":{"catalog_source":"litellm","upstream_key":"claude-4-opus-20250514","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":32000,"deprecation_date":"2026-06-15","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-4-sonnet-20250514","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"claude-4-sonnet-20250514","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":64000,"deprecation_date":"2026-06-15","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-fable-5","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":5000,"meta":{"catalog_source":"litellm","upstream_key":"claude-fable-5","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-haiku-4-5","billing_mode":"token","input_cents_per_1m":100,"output_cents_per_1m":500,"meta":{"catalog_source":"litellm","upstream_key":"claude-haiku-4-5","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-haiku-4-5-20251001","billing_mode":"token","input_cents_per_1m":100,"output_cents_per_1m":500,"meta":{"catalog_source":"litellm","upstream_key":"claude-haiku-4-5-20251001","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-mythos-5","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":5000,"meta":{"catalog_source":"litellm","upstream_key":"claude-mythos-5","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-mythos-preview","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":5000,"meta":{"catalog_source":"litellm","upstream_key":"claude-mythos-preview","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-1","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":7500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-1","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":32000,"deprecation_date":"2026-08-05","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-1-20250805","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":7500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-1-20250805","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":32000,"deprecation_date":"2026-08-05","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-20250514","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":7500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-20250514","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":32000,"deprecation_date":"2026-06-15","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-5","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-5","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-5-20251101","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-5-20251101","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-6","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-6","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-6-20260205","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-6-20260205","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-7","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-7","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-7-20260416","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-7-20260416","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-4-8","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-4-8","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-opus-5","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":2500,"meta":{"catalog_source":"litellm","upstream_key":"claude-opus-5","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-sonnet-4-20250514","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"claude-sonnet-4-20250514","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":64000,"deprecation_date":"2026-06-15","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-sonnet-4-5","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"claude-sonnet-4-5","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-sonnet-4-5-20250929","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"claude-sonnet-4-5-20250929","upstream_provider":"anthropic","mode":"chat","context_tokens":200000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-sonnet-4-6","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"claude-sonnet-4-6","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":64000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"anthropic","match_model":"claude-sonnet-5","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"claude-sonnet-5","upstream_provider":"anthropic","mode":"chat","context_tokens":1000000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true,"computer_use":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"chatgpt-4o-latest","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"chatgpt-4o-latest","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"deprecation_date":"2026-02-17","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"codex-mini-latest","billing_mode":"token","input_cents_per_1m":150,"output_cents_per_1m":600,"meta":{"catalog_source":"litellm","upstream_key":"codex-mini-latest","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-02-12","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-3.5-turbo","billing_mode":"token","input_cents_per_1m":50,"output_cents_per_1m":150,"meta":{"catalog_source":"litellm","upstream_key":"gpt-3.5-turbo","upstream_provider":"openai","mode":"chat","context_tokens":16385,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-3.5-turbo-0125","billing_mode":"token","input_cents_per_1m":50,"output_cents_per_1m":150,"meta":{"catalog_source":"litellm","upstream_key":"gpt-3.5-turbo-0125","upstream_provider":"openai","mode":"chat","context_tokens":16385,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-3.5-turbo-1106","billing_mode":"token","input_cents_per_1m":100,"output_cents_per_1m":200,"meta":{"catalog_source":"litellm","upstream_key":"gpt-3.5-turbo-1106","upstream_provider":"openai","mode":"chat","context_tokens":16385,"max_output_tokens":4096,"deprecation_date":"2026-09-28","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-3.5-turbo-16k","billing_mode":"token","input_cents_per_1m":300,"output_cents_per_1m":400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-3.5-turbo-16k","upstream_provider":"openai","mode":"chat","context_tokens":16385,"max_output_tokens":4096,"capabilities":{"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":6000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4","upstream_provider":"openai","mode":"chat","context_tokens":8192,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-0125-preview","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-0125-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"deprecation_date":"2026-03-26","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-0314","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":6000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-0314","upstream_provider":"openai","mode":"chat","context_tokens":8192,"max_output_tokens":4096,"deprecation_date":"2026-03-26"}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-0613","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":6000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-0613","upstream_provider":"openai","mode":"chat","context_tokens":8192,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-1106-preview","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-1106-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"prompt_caching":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-turbo","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-turbo","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-turbo-2024-04-09","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-turbo-2024-04-09","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4-turbo-preview","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4-turbo-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"capabilities":{"function_calling":true,"prompt_caching":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4.1","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":800,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4.1","upstream_provider":"openai","mode":"chat","context_tokens":1047576,"max_output_tokens":32768,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4.1-2025-04-14","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":800,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4.1-2025-04-14","upstream_provider":"openai","mode":"chat","context_tokens":1047576,"max_output_tokens":32768,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4.1-mini","billing_mode":"token","input_cents_per_1m":40,"output_cents_per_1m":160,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4.1-mini","upstream_provider":"openai","mode":"chat","context_tokens":1047576,"max_output_tokens":32768,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4.1-mini-2025-04-14","billing_mode":"token","input_cents_per_1m":40,"output_cents_per_1m":160,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4.1-mini-2025-04-14","upstream_provider":"openai","mode":"chat","context_tokens":1047576,"max_output_tokens":32768,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4.1-nano","billing_mode":"token","input_cents_per_1m":10,"output_cents_per_1m":40,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4.1-nano","upstream_provider":"openai","mode":"chat","context_tokens":1047576,"max_output_tokens":32768,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4.1-nano-2025-04-14","billing_mode":"token","input_cents_per_1m":10,"output_cents_per_1m":40,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4.1-nano-2025-04-14","upstream_provider":"openai","mode":"chat","context_tokens":1047576,"max_output_tokens":32768,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-2024-05-13","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-2024-05-13","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":4096,"deprecation_date":"2026-10-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-2024-08-06","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-2024-08-06","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-2024-11-20","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-2024-11-20","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-audio-preview","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-audio-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"function_calling":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-audio-preview-2024-12-17","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-audio-preview-2024-12-17","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"function_calling":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-audio-preview-2025-06-03","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-audio-preview-2025-06-03","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"function_calling":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-mini","billing_mode":"token","input_cents_per_1m":15,"output_cents_per_1m":60,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-mini","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-mini-2024-07-18","billing_mode":"token","input_cents_per_1m":15,"output_cents_per_1m":60,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-mini-2024-07-18","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-mini-audio-preview","billing_mode":"token","input_cents_per_1m":15,"output_cents_per_1m":60,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-mini-audio-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"function_calling":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-mini-audio-preview-2024-12-17","billing_mode":"token","input_cents_per_1m":15,"output_cents_per_1m":60,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-mini-audio-preview-2024-12-17","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"function_calling":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-mini-search-preview","billing_mode":"token","input_cents_per_1m":15,"output_cents_per_1m":60,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-mini-search-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-mini-search-preview-2025-03-11","billing_mode":"token","input_cents_per_1m":15,"output_cents_per_1m":60,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-mini-search-preview-2025-03-11","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-07-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-search-preview","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-search-preview","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-4o-search-preview-2025-03-11","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-4o-search-preview-2025-03-11","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-07-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-2025-08-07","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-2025-08-07","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-12-11","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-chat","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-chat","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"reasoning":true,"function_calling":false,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-chat-latest","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-chat-latest","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":false,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-codex","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-codex","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-mini","billing_mode":"token","input_cents_per_1m":25,"output_cents_per_1m":200,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-mini","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-mini-2025-08-07","billing_mode":"token","input_cents_per_1m":25,"output_cents_per_1m":200,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-mini-2025-08-07","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-12-11","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-nano","billing_mode":"token","input_cents_per_1m":5,"output_cents_per_1m":40,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-nano","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-nano-2025-08-07","billing_mode":"token","input_cents_per_1m":5,"output_cents_per_1m":40,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-nano-2025-08-07","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-12-11","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-pro","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":12000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-pro","upstream_provider":"openai","mode":"responses","context_tokens":400000,"max_output_tokens":272000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-pro-2025-10-06","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":12000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-pro-2025-10-06","upstream_provider":"openai","mode":"responses","context_tokens":400000,"max_output_tokens":272000,"deprecation_date":"2026-12-11","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-search-api","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-search-api","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5-search-api-2025-10-14","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5-search-api-2025-10-14","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.1","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.1","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.1-2025-11-13","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.1-2025-11-13","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.1-chat-latest","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.1-chat-latest","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":false,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.1-codex","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.1-codex","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.1-codex-max","billing_mode":"token","input_cents_per_1m":125,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.1-codex-max","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.1-codex-mini","billing_mode":"token","input_cents_per_1m":25,"output_cents_per_1m":200,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.1-codex-mini","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.2","billing_mode":"token","input_cents_per_1m":175,"output_cents_per_1m":1400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.2","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.2-2025-12-11","billing_mode":"token","input_cents_per_1m":175,"output_cents_per_1m":1400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.2-2025-12-11","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.2-chat-latest","billing_mode":"token","input_cents_per_1m":175,"output_cents_per_1m":1400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.2-chat-latest","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-08-10","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.2-codex","billing_mode":"token","input_cents_per_1m":175,"output_cents_per_1m":1400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.2-codex","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"deprecation_date":"2026-07-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.2-pro","billing_mode":"token","input_cents_per_1m":2100,"output_cents_per_1m":16800,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.2-pro","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.2-pro-2025-12-11","billing_mode":"token","input_cents_per_1m":2100,"output_cents_per_1m":16800,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.2-pro-2025-12-11","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.3-chat-latest","billing_mode":"token","input_cents_per_1m":175,"output_cents_per_1m":1400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.3-chat-latest","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-08-10","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.3-codex","billing_mode":"token","input_cents_per_1m":175,"output_cents_per_1m":1400,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.3-codex","upstream_provider":"openai","mode":"responses","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-2026-03-05","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1500,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-2026-03-05","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-mini","billing_mode":"token","input_cents_per_1m":75,"output_cents_per_1m":450,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-mini","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-mini-2026-03-17","billing_mode":"token","input_cents_per_1m":75,"output_cents_per_1m":450,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-mini-2026-03-17","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-nano","billing_mode":"token","input_cents_per_1m":20,"output_cents_per_1m":125,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-nano","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-nano-2026-03-17","billing_mode":"token","input_cents_per_1m":20,"output_cents_per_1m":125,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-nano-2026-03-17","upstream_provider":"openai","mode":"chat","context_tokens":272000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-pro","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":18000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-pro","upstream_provider":"openai","mode":"responses","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":false,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.4-pro-2026-03-05","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":18000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.4-pro-2026-03-05","upstream_provider":"openai","mode":"responses","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":false,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.5","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.5","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.5-2026-04-23","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.5-2026-04-23","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.5-pro","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":18000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.5-pro","upstream_provider":"openai","mode":"responses","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":false,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.5-pro-2026-04-23","billing_mode":"token","input_cents_per_1m":3000,"output_cents_per_1m":18000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.5-pro-2026-04-23","upstream_provider":"openai","mode":"responses","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":false,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.6","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.6","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.6-luna","billing_mode":"token","input_cents_per_1m":20,"output_cents_per_1m":120,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.6-luna","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.6-sol","billing_mode":"token","input_cents_per_1m":500,"output_cents_per_1m":3000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.6-sol","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-5.6-terra","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":1200,"meta":{"catalog_source":"litellm","upstream_key":"gpt-5.6-terra","upstream_provider":"openai","mode":"chat","context_tokens":1050000,"max_output_tokens":128000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-audio","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-audio","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"reasoning":false,"function_calling":true,"vision":false,"prompt_caching":false,"response_schema":false}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-audio-1.5","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-audio-1.5","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"reasoning":false,"function_calling":true,"vision":false,"prompt_caching":false,"response_schema":false}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-audio-2025-08-28","billing_mode":"token","input_cents_per_1m":250,"output_cents_per_1m":1000,"meta":{"catalog_source":"litellm","upstream_key":"gpt-audio-2025-08-28","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"reasoning":false,"function_calling":true,"vision":false,"prompt_caching":false,"response_schema":false}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-audio-mini","billing_mode":"token","input_cents_per_1m":60,"output_cents_per_1m":240,"meta":{"catalog_source":"litellm","upstream_key":"gpt-audio-mini","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2027-01-20","capabilities":{"reasoning":false,"function_calling":true,"vision":false,"prompt_caching":false,"response_schema":false}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-audio-mini-2025-10-06","billing_mode":"token","input_cents_per_1m":60,"output_cents_per_1m":240,"meta":{"catalog_source":"litellm","upstream_key":"gpt-audio-mini-2025-10-06","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"deprecation_date":"2026-07-23","capabilities":{"reasoning":false,"function_calling":true,"vision":false,"prompt_caching":false,"response_schema":false}}},
    {"match_provider_kind":"openai_compatible","match_model":"gpt-audio-mini-2025-12-15","billing_mode":"token","input_cents_per_1m":60,"output_cents_per_1m":240,"meta":{"catalog_source":"litellm","upstream_key":"gpt-audio-mini-2025-12-15","upstream_provider":"openai","mode":"chat","context_tokens":128000,"max_output_tokens":16384,"capabilities":{"reasoning":false,"function_calling":true,"vision":false,"prompt_caching":false,"response_schema":false}}},
    {"match_provider_kind":"openai_compatible","match_model":"o1","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":6000,"meta":{"catalog_source":"litellm","upstream_key":"o1","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o1-2024-12-17","billing_mode":"token","input_cents_per_1m":1500,"output_cents_per_1m":6000,"meta":{"catalog_source":"litellm","upstream_key":"o1-2024-12-17","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o1-pro","billing_mode":"token","input_cents_per_1m":15000,"output_cents_per_1m":60000,"meta":{"catalog_source":"litellm","upstream_key":"o1-pro","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o1-pro-2025-03-19","billing_mode":"token","input_cents_per_1m":15000,"output_cents_per_1m":60000,"meta":{"catalog_source":"litellm","upstream_key":"o1-pro-2025-03-19","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":800,"meta":{"catalog_source":"litellm","upstream_key":"o3","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-2025-04-16","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":800,"meta":{"catalog_source":"litellm","upstream_key":"o3-2025-04-16","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-12-11","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-deep-research","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":4000,"meta":{"catalog_source":"litellm","upstream_key":"o3-deep-research","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-07-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-deep-research-2025-06-26","billing_mode":"token","input_cents_per_1m":1000,"output_cents_per_1m":4000,"meta":{"catalog_source":"litellm","upstream_key":"o3-deep-research-2025-06-26","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-07-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-mini","billing_mode":"token","input_cents_per_1m":110,"output_cents_per_1m":440,"meta":{"catalog_source":"litellm","upstream_key":"o3-mini","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":false,"prompt_caching":true,"response_schema":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-mini-2025-01-31","billing_mode":"token","input_cents_per_1m":110,"output_cents_per_1m":440,"meta":{"catalog_source":"litellm","upstream_key":"o3-mini-2025-01-31","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":false,"prompt_caching":true,"response_schema":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-pro","billing_mode":"token","input_cents_per_1m":2000,"output_cents_per_1m":8000,"meta":{"catalog_source":"litellm","upstream_key":"o3-pro","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o3-pro-2025-06-10","billing_mode":"token","input_cents_per_1m":2000,"output_cents_per_1m":8000,"meta":{"catalog_source":"litellm","upstream_key":"o3-pro-2025-06-10","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-12-11","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o4-mini","billing_mode":"token","input_cents_per_1m":110,"output_cents_per_1m":440,"meta":{"catalog_source":"litellm","upstream_key":"o4-mini","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o4-mini-2025-04-16","billing_mode":"token","input_cents_per_1m":110,"output_cents_per_1m":440,"meta":{"catalog_source":"litellm","upstream_key":"o4-mini-2025-04-16","upstream_provider":"openai","mode":"chat","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-10-23","capabilities":{"reasoning":true,"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o4-mini-deep-research","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":800,"meta":{"catalog_source":"litellm","upstream_key":"o4-mini-deep-research","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-07-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}},
    {"match_provider_kind":"openai_compatible","match_model":"o4-mini-deep-research-2025-06-26","billing_mode":"token","input_cents_per_1m":200,"output_cents_per_1m":800,"meta":{"catalog_source":"litellm","upstream_key":"o4-mini-deep-research-2025-06-26","upstream_provider":"openai","mode":"responses","context_tokens":200000,"max_output_tokens":100000,"deprecation_date":"2026-07-23","capabilities":{"function_calling":true,"vision":true,"prompt_caching":true,"response_schema":true,"web_search":true,"pdf_input":true}}}
  ]$catalog$::jsonb
);
