import { describe, expect, it } from "vitest";

import sidebars from "../sidebars";
import { SECTIONS } from "../site.constants";

describe("sidebars.ts", () => {
  it("exports exactly the three section sidebars", () => {
    expect(Object.keys(sidebars)).toEqual(["userGuide", "administration", "cli"]);
  });

  it("generates each sidebar from its own section folder", () => {
    for (const section of SECTIONS) {
      expect(sidebars[section.sidebarId], section.sidebarId).toEqual([
        { type: "autogenerated", dirName: section.dir },
      ]);
    }
  });

  it("names the sections and their folders as roadmap decision D2 states", () => {
    expect(SECTIONS.map((section) => [section.label, section.dir])).toEqual([
      ["User Guide", "user-guide"],
      ["Administration", "administration"],
      ["CLI", "cli"],
    ]);
  });
});
