/**
 * A roadmap version's life in the repository (CM.5,
 * [#624](https://github.com/NobuData/ouroboros/issues/624)).
 *
 * ```
 * pending ──▶ pr_open ──▶ committed ──▶ drift_detected
 *    │           │
 *    │           └──▶ pending          (the PR was closed unmerged)
 *    └──────────────▶ committed        (direct commit — the opt-in — or the file already holds it)
 * ```
 *
 * **The repository is reviewed, not written to.** A version is committed to the document's own
 * branch and proposed as a pull request; a later version lands on the same branch and updates the
 * same PR. Committing straight to the default branch happens only when the workspace opted in
 * (`roadmap_pipeline_settings.direct_commit`) **and** the workspace is not in dry-run — under
 * dry-run the PR is opened as a draft, like every PR the product opens.
 *
 * **A repository that cannot be reached is not a failure of the document.** The version is
 * stored before anything is projected, so a refused token or a tracker without a repository
 * leaves it `pending` with the reason said; {@link RoadmapProjector.settle} tries again later.
 */

import { Injectable, Logger } from "@nestjs/common";

import { describeForLog } from "../../errors/failure";
import { OrgPolicyService } from "../../policies/org-policy.service";
import { TicketSourceError } from "../../ticket-sources/ticket-source.errors";
import type { RepoDocState } from "../../ticket-sources/ticket-source.repo-doc";
import { ProviderRepoGateway, type RepoGateway, type RoadmapRepo } from "./pipeline.repo";
import {
  PipelineRepository,
  type DocRow,
  type PipelineStore,
  type RepoProjection,
  type VersionRow,
} from "./pipeline.repository";
import { itemsOf } from "./roadmap.structure";

/** Where a document is written unless the request says otherwise. */
export const DEFAULT_ROADMAP_PATH = "docs/ROADMAP.md";

/** A commit sha as V113 stores one. */
const SHA = /^[0-9a-f]{7,40}$/;

/** What a projection attempt came to. */
export interface ProjectionOutcome {
  /** The version's projection now. */
  readonly projection: RepoProjection;
  /** Why it could not be moved, in a sentence — null when it is where it should be. */
  readonly problem: string | null;
}

/** What the file in the repository holds, when it could be read. */
export interface RepoReading {
  /** The file on the default branch, or null when it is not there. */
  readonly file: RepoDocState | null;
}

/**
 * The branch a document's versions are committed to.
 *
 * @param docId - The document.
 * @returns `ouroboros/roadmap-<first eight of the id>`.
 */
export function roadmapBranch(docId: string): string {
  return `ouroboros/roadmap-${docId.slice(0, 8)}`;
}

/**
 * The PR's title for a version.
 *
 * @param doc - The document.
 * @param version - The version.
 * @returns `docs: <title> (v2)`.
 */
export function prTitle(doc: DocRow, version: VersionRow): string {
  return `docs: ${doc.title} (v${String(version.version)})`.slice(0, 256);
}

/**
 * The PR's description for a version.
 *
 * @param doc - The document.
 * @param version - The version.
 * @returns What the file is, where it came from, and why not to edit it by hand.
 */
export function prBody(doc: DocRow, version: VersionRow): string {
  const items = itemsOf(version.structure).length;
  const milestones = version.structure.milestones.length;

  return [
    `**${doc.title}** — version ${String(version.version)}, generated by \`${version.generatedBy}\`.`,
    "",
    `${String(milestones)} milestone${milestones === 1 ? "" : "s"} · ${String(items)} item${items === 1 ? "" : "s"}`,
    "",
    `\`${version.projection.path}\` is a projection of the roadmap Ouroboros holds. To change it, ` +
      "suggest a change on the Research page and apply it; a hand edit of the file is reported as drift.",
  ].join("\n");
}

@Injectable()
export class RoadmapProjector {
  private readonly logger = new Logger(RoadmapProjector.name);

  /** The stores behind their seams. */
  private readonly store: PipelineStore;
  private readonly gateway: RepoGateway;

  /**
   * @param repository - Documents, versions and the policy.
   * @param gateway - Opens the repository.
   * @param policy - The workspace's dry-run switch.
   */
  constructor(
    repository: PipelineRepository,
    gateway: ProviderRepoGateway,
    private readonly policy: OrgPolicyService,
  ) {
    this.store = repository;
    this.gateway = gateway;
  }

  /**
   * Bring a version's projection as far as the repository allows: project a `pending` one, and
   * follow an open PR to `committed` or back to `pending`.
   *
   * @param doc - The document.
   * @param version - Its current version.
   * @returns Where the projection stands, and why it could not move when it could not.
   */
  async settle(doc: DocRow, version: VersionRow): Promise<ProjectionOutcome> {
    const { state } = version.projection;

    if (state !== "pending" && state !== "pr_open") {
      return { projection: version.projection, problem: null };
    }

    return this.inRepository(doc, version, (repo) =>
      state === "pending" ? this.project(repo, doc, version) : this.follow(repo, version),
    );
  }

  /**
   * Read the document's file from the default branch.
   *
   * @param doc - The document.
   * @param version - Its current version.
   * @returns The file, or null when the repository could not be read — which is not a drift.
   */
  async read(doc: DocRow, version: VersionRow): Promise<RepoReading | null> {
    let reading: RepoReading | null = null;

    await this.inRepository(doc, version, async (repo) => {
      reading = {
        file: await repo.fileAt(version.projection.path, await repo.defaultBranch()),
      };

      return version.projection;
    });

    return reading;
  }

  /**
   * Record that a committed version has drifted.
   *
   * @param doc - The document.
   * @param version - Its current version, `committed`.
   * @param observedSha - The repository commit the drift was seen at, when the file was read.
   * @returns The projection, now `drift_detected`; unchanged for a version that is not committed.
   */
  async markDrift(
    doc: DocRow,
    version: VersionRow,
    observedSha: string | null,
  ): Promise<RepoProjection> {
    const current = version.projection;

    if (current.state !== "committed" || current.committed_sha === null) return current;

    const projection: RepoProjection = {
      ...current,
      state: "drift_detected",
      observed_sha:
        observedSha !== null && SHA.test(observedSha) ? observedSha : current.committed_sha,
    };

    await this.store.setProjection(doc.id, version.version, projection);

    return projection;
  }

  /**
   * Put a pending version into the repository: a commit and a pull request, or — opted in and not
   * in dry-run — a commit on the default branch.
   *
   * @param repo - The repository, opened.
   * @param doc - The document.
   * @param version - The version.
   * @returns The projection the version should now carry.
   */
  private async project(
    repo: RoadmapRepo,
    doc: DocRow,
    version: VersionRow,
  ): Promise<RepoProjection> {
    const { path } = version.projection;
    const base = await repo.defaultBranch();
    const landed = await repo.fileAt(path, base);

    // The default branch already holds exactly this version: nothing to propose.
    if (
      landed?.content === version.markdown &&
      landed.commitSha !== null &&
      SHA.test(landed.commitSha)
    ) {
      return { ...version.projection, state: "committed", committed_sha: landed.commitSha };
    }

    const [settings, dryRun] = await Promise.all([
      this.store.settings(doc.organizationId),
      this.policy.dryRunNow(doc.organizationId),
    ]);
    const message = `docs: roadmap v${String(version.version)} — ${doc.title}`;

    if (settings.directCommit && !dryRun) {
      const commit = await repo.commitFile({
        path,
        content: version.markdown,
        message,
        branch: base,
        base,
      });

      if (!SHA.test(commit.commitSha)) throw new Error("the host answered a commit with no sha");

      return {
        ...version.projection,
        state: "committed",
        pr_ref: null,
        committed_sha: commit.commitSha,
      };
    }

    const branch = roadmapBranch(doc.id);

    await repo.commitFile({ path, content: version.markdown, message, branch, base });

    const title = prTitle(doc, version);
    const body = prBody(doc, version);
    const pr = await repo.openPR({ branch, base, title, body, draft: dryRun });

    // An earlier version's PR is still open for this branch: it now proposes this version.
    await repo.updatePR(pr.number, { title, body });

    return { ...version.projection, state: "pr_open", pr_ref: `#${String(pr.number)}` };
  }

  /**
   * Follow an open PR: merged is `committed`, closed unmerged is `pending` again.
   *
   * @param repo - The repository, opened.
   * @param version - The version, `pr_open`.
   * @returns The projection the version should now carry.
   */
  private async follow(repo: RoadmapRepo, version: VersionRow): Promise<RepoProjection> {
    const current = version.projection;
    const number = Number((current.pr_ref ?? "").replace(/^#/, ""));

    if (!Number.isInteger(number) || number < 1) return current;

    const state = await repo.prState(number);

    if (state === "closed") return { ...current, state: "pending", pr_ref: null };
    if (state !== "merged") return current;

    const landed = await repo.fileAt(current.path, await repo.defaultBranch());

    return landed?.commitSha !== null &&
      landed?.commitSha !== undefined &&
      SHA.test(landed.commitSha)
      ? { ...current, state: "committed", committed_sha: landed.commitSha }
      : current;
  }

  /**
   * Run work against the document's repository, store the projection it answers, and turn a
   * refusal into a sentence.
   *
   * @param doc - The document.
   * @param version - Its current version.
   * @param work - What to do; answers the projection the version should carry.
   * @returns The outcome.
   */
  private async inRepository(
    doc: DocRow,
    version: VersionRow,
    work: (repo: RoadmapRepo) => Promise<RepoProjection>,
  ): Promise<ProjectionOutcome> {
    const unchanged = (problem: string): ProjectionOutcome => ({
      projection: version.projection,
      problem,
    });

    if (doc.targetSourceId === null) {
      return unchanged("The roadmap's ticket source was removed, so it has no repository.");
    }

    const source = await this.store.source(doc.organizationId, doc.targetSourceId);

    if (source === undefined) {
      return unchanged("The roadmap's ticket source was removed, so it has no repository.");
    }

    let projection: RepoProjection | undefined;

    try {
      projection = await this.gateway.open(source, work);
    } catch (error) {
      if (!TicketSourceError.is(error)) throw error;

      this.logger.warn(
        `roadmap ${doc.id} v${String(version.version)} could not reach its repository ` +
          `(${error.errorClass}).`,
        describeForLog(error),
      );

      return unchanged(`The repository refused the request (${error.errorClass}): ${error.detail}`);
    }

    if (projection === undefined) {
      return unchanged(`${source.displayName} has no repository a document can be written to.`);
    }

    if (JSON.stringify(projection) !== JSON.stringify(version.projection)) {
      await this.store.setProjection(doc.id, version.version, projection);
    }

    return { projection, problem: null };
  }
}
