/**
 * The embedded secrets ruleset — infrastructure option **3-A**, versioned in-repo.
 *
 * AP.3 ([#305](https://github.com/NobuData/ouroboros/issues/305)). A gitleaks-class set of
 * well-known credential formats plus keyword proximity — option 3-A budgets *roughly 150*, and
 * {@link SECRETS_RULESET_DISCLOSURE} counts what this version actually holds — run over the
 * *added* lines of a reported diff. It takes milliseconds, needs no external binary, and gives the same verdict
 * for the same diff every time — which is what lets a verdict be compared across re-evaluations.
 *
 * ---------------------------------------------------------------------------
 * **What it does not catch, said where the rules are.**
 *
 * A regex ruleset recognises a credential by its *shape*: a prefix (`AKIA`, `ghp_`, `xoxb-`), a
 * fixed length and alphabet, or a keyword sitting next to a value. A high-entropy secret with no
 * recognisable format — a random database password, an HMAC key someone generated by hand, a
 * token from a provider that is not listed here — has no shape to recognise. That is a recall
 * class of roughly **70 %**: this ruleset finds the common catastrophes (cloud keys, source-host
 * tokens, private key blocks) and misses the rest by construction.
 *
 * So a `secrets` pass means *"no known credential format was found in the added lines"* and
 * **never** *"this diff contains no secrets"*. {@link SECRETS_RULESET_DISCLOSURE} is that
 * sentence as data, for the Guardrails card's tooltip (#313), so a green tick never claims more
 * than the scan earned. Verified scanning — which does better and costs outbound calls carrying
 * candidate credentials — is AR.5 ([#319](https://github.com/NobuData/ouroboros/issues/319)).
 *
 * ---------------------------------------------------------------------------
 * **How a rule is shaped.**
 *
 *   * **`format` rules** carry their own evidence — a prefix or a structure that is the
 *     credential's signature. Their keywords are the literal prefix, used only as a cheap
 *     prefilter: a rule whose keyword is not in the text is never run.
 *   * **`near` rules** match a value with no signature of its own (32 hex characters, a UUID),
 *     which would fire on every checksum and id in a codebase. They count only when one of their
 *     keywords appears within {@link PROXIMITY_WINDOW} characters **before** the value on the same
 *     line — `DATADOG_API_KEY=…` fires, a bare hash in a lockfile does not. That is the keyword
 *     proximity the issue asks for, and it is where most of the false positives are cut.
 *   * **Generic rules** (`generic-password`, `generic-api-key`, the URI credentials) capture the
 *     value and discard obvious placeholders — `changeme`, `${PASSWORD}`, `<token>`, `xxxx` — and
 *     values with no digit in them, which is what a sentence or an identifier looks like.
 *
 * Every quantifier that is followed by more pattern is **bounded**, so no rule backtracks
 * quadratically on a long minified line.
 *
 * ---------------------------------------------------------------------------
 * **Versioning.** {@link SECRETS_RULESET_VERSION} is recorded on every `secrets` verdict
 * (`guardrail_evaluations.ruleset_version`), so *"the same diff under a newer ruleset"* is a
 * checkable explanation for a verdict that changed while the code did not. **Bump it with every
 * edit to {@link SECRET_RULES}** — adding, removing, or changing a pattern or a keyword.
 *
 * Rule ids are the evidence's `rule_id` and are held by V048 to
 * `^[a-z][a-z0-9]*(-[a-z0-9]+)*$`, at most 64 characters — the spec asserts every one does.
 */

/** The ruleset's version, as `ruleset_version` records it. `v3` is the card's *secrets ruleset v3*. */
export const SECRETS_RULESET_VERSION = "v3";

/**
 * How far before a `near` rule's value its keyword may sit, in characters on the same line.
 *
 * Wide enough for `export DATADOG_API_KEY = "` and `datadog: { api_key: '`, narrow enough that a
 * keyword at the start of a long line does not vouch for a hash at its end.
 */
export const PROXIMITY_WINDOW = 64;

/** One rule of the ruleset. */
export interface SecretRule {
  /** The evidence's `rule_id` — lower-case, hyphenated, at most 64 characters. */
  readonly id: string;
  /** What it finds, for a person reading the ruleset. Never rendered with a match. */
  readonly description: string;
  /** The pattern. Always global, so a line with two credentials reports the first and moves on. */
  readonly pattern: RegExp;
  /**
   * Lower-case literals, at least one of which must appear in the text for the rule to run.
   *
   * For a `format` rule they are the prefilter; for a `near` rule they are also the proximity
   * anchor.
   */
  readonly keywords: readonly string[];
  /** Whether a keyword must sit within {@link PROXIMITY_WINDOW} characters before the match. */
  readonly proximity: boolean;
  /**
   * Which capture group holds the value, for rules that screen out placeholders.
   *
   * Absent for rules whose whole match is a signature — nobody writes `AKIA` + sixteen
   * base-32 characters as a placeholder.
   */
  readonly valueGroup?: number;
}

/**
 * A rule whose match is its own signature.
 *
 * @param id - The rule id.
 * @param description - What it finds.
 * @param source - The pattern's source. Case-sensitive: formats are.
 * @param keywords - Lower-case literals the text must contain for the rule to run.
 * @returns The rule.
 */
function format(
  id: string,
  description: string,
  source: string,
  keywords: readonly string[],
): SecretRule {
  return { id, description, pattern: new RegExp(source, "g"), keywords, proximity: false };
}

/**
 * A rule whose value has no signature, and so needs a keyword beside it.
 *
 * The value is wrapped in alphanumeric look-arounds, so `[a-f0-9]{32}` matches a 32-character
 * hex token and not 32 characters out of the middle of a 64-character one.
 *
 * @param id - The rule id.
 * @param description - What it finds.
 * @param keywords - Lower-case literals, one of which must precede the value within
 *   {@link PROXIMITY_WINDOW} characters.
 * @param value - The value's pattern source.
 * @returns The rule.
 */
function near(
  id: string,
  description: string,
  keywords: readonly string[],
  value: string,
): SecretRule {
  return {
    id,
    description,
    pattern: new RegExp(`(?<![A-Za-z0-9])(?:${value})(?![A-Za-z0-9])`, "g"),
    keywords,
    proximity: true,
  };
}

/** A UUID, which several providers use as a bare API key. */
const UUID = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}";

/**
 * The keywords that make a quoted value a candidate for the two generic rules.
 *
 * Shared by the pattern and the prefilter so the two cannot disagree about what a keyword is.
 */
const PASSWORD_WORDS = ["password", "passwd", "pwd"] as const;
const API_KEY_WORDS = [
  "secret",
  "token",
  "api_key",
  "api-key",
  "apikey",
  "access_key",
  "access-key",
  "private_key",
  "client_secret",
  "auth_key",
] as const;

/**
 * Build a generic `keyword = "value"` rule.
 *
 * @param id - The rule id.
 * @param description - What it finds.
 * @param words - The keywords, lower-case, matched case-insensitively.
 * @returns The rule, capturing the quoted value as group 1.
 */
function assignment(id: string, description: string, words: readonly string[]): SecretRule {
  const alternation = words.map((word) => word.replace(/[-_]/g, "[-_]?")).join("|");

  return {
    id,
    description,
    pattern: new RegExp(
      `(?:${alternation})[A-Za-z0-9_-]{0,20}["']?\\s{0,5}(?:[:=]|:=|=>)\\s{0,5}["'\`]([^"'\`\\s]{8,200})["'\`]`,
      "gi",
    ),
    keywords: words,
    proximity: false,
    valueGroup: 1,
  };
}

/**
 * Build a credentials-in-a-URI rule — `scheme://user:password@host`.
 *
 * @param id - The rule id.
 * @param description - What it finds.
 * @param schemes - The scheme alternation's source.
 * @param keywords - Lower-case scheme literals for the prefilter.
 * @returns The rule, capturing the password as group 1.
 */
function uriCredential(
  id: string,
  description: string,
  schemes: string,
  keywords: readonly string[],
): SecretRule {
  return {
    id,
    description,
    pattern: new RegExp(`\\b(?:${schemes})://[^\\s:/@]{1,256}:([^\\s/@]{3,256})@`, "gi"),
    keywords,
    proximity: false,
    valueGroup: 1,
  };
}

/**
 * The ruleset.
 *
 * Grouped by what the credential opens, because that is how a person scanning this list looks
 * for a provider. Order does not affect verdicts: every rule runs, and findings are ordered by
 * path and line.
 */
export const SECRET_RULES: readonly SecretRule[] = [
  // --- cloud providers --------------------------------------------------------------------
  format(
    "aws-access-key-id",
    "AWS access key id (long-lived, temporary, and service prefixes)",
    "\\b(?:AKIA|ASIA|ABIA|ACCA|A3T[A-Z0-9])[A-Z2-7]{16}\\b",
    ["akia", "asia", "abia", "acca", "a3t"],
  ),
  near(
    "aws-secret-access-key",
    "AWS secret access key beside its keyword",
    ["aws_secret", "aws-secret", "secret_access_key", "secretaccesskey", "aws secret"],
    "[A-Za-z0-9/+]{40}",
  ),
  near(
    "aws-session-token",
    "AWS session token beside its keyword",
    ["aws_session_token", "x-amz-security-token", "sessiontoken"],
    "[A-Za-z0-9/+=]{100,1200}",
  ),
  format("aws-mws-key", "Amazon Marketplace Web Service key", `amzn\\.mws\\.${UUID}`, [
    "amzn.mws.",
  ]),
  format("gcp-api-key", "Google Cloud / Firebase API key", "\\bAIza[0-9A-Za-z_-]{35}\\b", ["aiza"]),
  format(
    "gcp-service-account",
    "Google service-account key file",
    '"type"\\s{0,5}:\\s{0,5}"service_account"',
    ["service_account"],
  ),
  format(
    "gcp-oauth-client-secret",
    "Google OAuth client secret",
    "\\bGOCSPX-[A-Za-z0-9_-]{28}\\b",
    ["gocspx-"],
  ),
  format(
    "google-oauth-access-token",
    "Google OAuth access token",
    "\\bya29\\.[0-9A-Za-z_-]{20,400}",
    ["ya29."],
  ),
  format(
    "azure-storage-account-key",
    "Azure storage account key in a connection string",
    "AccountKey=[A-Za-z0-9+/]{86}==",
    ["accountkey="],
  ),
  format("azure-sas-token", "Azure shared access signature", "[?&]sig=[A-Za-z0-9%+/]{40,200}", [
    "sig=",
  ]),
  format(
    "azure-ad-client-secret",
    "Azure AD (Entra) client secret",
    "\\b[A-Za-z0-9_~.]{3}\\dQ~[A-Za-z0-9_~.-]{31,34}\\b",
    ["q~"],
  ),
  near(
    "azure-devops-pat",
    "Azure DevOps personal access token",
    ["azure", "devops", "ado_pat"],
    "[a-z2-7]{52}",
  ),
  format("digitalocean-pat", "DigitalOcean personal access token", "\\bdop_v1_[a-f0-9]{64}\\b", [
    "dop_v1_",
  ]),
  format("digitalocean-oauth-token", "DigitalOcean OAuth token", "\\bdoo_v1_[a-f0-9]{64}\\b", [
    "doo_v1_",
  ]),
  format("digitalocean-refresh-token", "DigitalOcean refresh token", "\\bdor_v1_[a-f0-9]{64}\\b", [
    "dor_v1_",
  ]),
  format("alibaba-access-key-id", "Alibaba Cloud access key id", "\\bLTAI[A-Za-z0-9]{20}\\b", [
    "ltai",
  ]),
  near("alibaba-secret-key", "Alibaba Cloud secret key", ["alibaba", "aliyun"], "[A-Za-z0-9]{30}"),
  near("ibm-cloud-api-key", "IBM Cloud API key", ["ibm"], "[A-Za-z0-9_-]{44}"),
  near("heroku-api-key", "Heroku API key (UUID form)", ["heroku"], UUID),
  format("heroku-api-key-v2", "Heroku API key", "\\bHRKU-AA[0-9A-Za-z_-]{58}\\b", ["hrku-"]),
  near(
    "cloudflare-api-token",
    "Cloudflare API token",
    ["cloudflare", "cf_api"],
    "[A-Za-z0-9_-]{40}",
  ),
  near(
    "cloudflare-global-api-key",
    "Cloudflare global API key",
    ["cloudflare", "cf_api"],
    "[a-f0-9]{37}",
  ),
  format(
    "cloudflare-origin-ca-key",
    "Cloudflare Origin CA key",
    "\\bv1\\.0-[a-f0-9]{24}-[a-f0-9]{146}\\b",
    ["v1.0-"],
  ),
  near("fastly-api-token", "Fastly API token", ["fastly"], "[A-Za-z0-9_-]{32}"),
  near("linode-api-token", "Linode API token", ["linode"], "[a-f0-9]{64}"),
  near("vultr-api-key", "Vultr API key", ["vultr"], "[A-Z0-9]{36}"),
  near("scaleway-secret-key", "Scaleway secret key", ["scaleway", "scw_secret"], UUID),
  format(
    "hashicorp-vault-service-token",
    "HashiCorp Vault service token",
    "\\bhvs\\.[A-Za-z0-9_-]{90,120}\\b",
    ["hvs."],
  ),
  format(
    "hashicorp-vault-batch-token",
    "HashiCorp Vault batch token",
    "\\bhvb\\.[A-Za-z0-9_-]{138,300}\\b",
    ["hvb."],
  ),
  format(
    "terraform-cloud-token",
    "Terraform Cloud / Enterprise API token",
    "\\b[A-Za-z0-9]{14}\\.atlasv1\\.[A-Za-z0-9_=-]{60,70}\\b",
    ["atlasv1"],
  ),
  format("pulumi-access-token", "Pulumi access token", "\\bpul-[a-f0-9]{40}\\b", ["pul-"]),
  format("doppler-token", "Doppler personal token", "\\bdp\\.pt\\.[A-Za-z0-9]{43}\\b", ["dp.pt."]),
  format("flyio-access-token", "Fly.io access token", "\\bfo1_[A-Za-z0-9_-]{43}\\b", ["fo1_"]),
  near("netlify-access-token", "Netlify access token", ["netlify"], "[A-Za-z0-9_-]{40,46}"),
  near("vercel-token", "Vercel token", ["vercel"], "[A-Za-z0-9]{24}"),
  format("render-api-key", "Render API key", "\\brnd_[A-Za-z0-9]{32}\\b", ["rnd_"]),
  format("supabase-access-token", "Supabase personal access token", "\\bsbp_[a-f0-9]{40}\\b", [
    "sbp_",
  ]),
  format(
    "planetscale-password",
    "PlanetScale database password",
    "\\bpscale_pw_[A-Za-z0-9_.-]{32,64}\\b",
    ["pscale_pw_"],
  ),
  format(
    "planetscale-api-token",
    "PlanetScale API token",
    "\\bpscale_tkn_[A-Za-z0-9_.-]{32,64}\\b",
    ["pscale_tkn_"],
  ),
  format(
    "planetscale-oauth-token",
    "PlanetScale OAuth token",
    "\\bpscale_oauth_[A-Za-z0-9_.-]{32,64}\\b",
    ["pscale_oauth_"],
  ),
  format("databricks-api-token", "Databricks API token", "\\bdapi[a-f0-9]{32}(?:-\\d)?\\b", [
    "dapi",
  ]),
  near("confluent-api-secret", "Confluent Cloud API secret", ["confluent"], "[A-Za-z0-9+/]{64}"),
  format("openshift-user-token", "OpenShift user token", "\\bsha256~[A-Za-z0-9_-]{43}\\b", [
    "sha256~",
  ]),
  format("scalingo-api-token", "Scalingo API token", "\\btk-us-[A-Za-z0-9_-]{48}\\b", ["tk-us-"]),
  format(
    "tailscale-key",
    "Tailscale API, auth or OAuth key",
    "\\btskey-(?:api|auth|client|scim|webhook)-[A-Za-z0-9]{10,20}-[A-Za-z0-9]{20,60}\\b",
    ["tskey-"],
  ),
  near("ngrok-authtoken", "ngrok auth token", ["ngrok"], "[A-Za-z0-9]{2}[A-Za-z0-9_]{40,50}"),
  format(
    "defined-networking-api-token",
    "Defined Networking API token",
    "\\bdnkey-[a-z0-9=_-]{26}-[a-z0-9=_-]{52}\\b",
    ["dnkey-"],
  ),
  format("yandex-api-key", "Yandex Cloud API key", "\\bAQVN[A-Za-z0-9_-]{35,38}\\b", ["aqvn"]),
  format(
    "yandex-access-token",
    "Yandex Cloud IAM token",
    "\\bt1\\.[A-Za-z0-9_-]{8,200}={0,2}\\.[A-Za-z0-9_-]{86}={0,2}",
    ["t1."],
  ),

  // --- source hosts, CI and package registries ----------------------------------------------
  format("github-pat", "GitHub personal access token (classic)", "\\bghp_[A-Za-z0-9]{36}\\b", [
    "ghp_",
  ]),
  format(
    "github-fine-grained-pat",
    "GitHub fine-grained personal access token",
    "\\bgithub_pat_[A-Za-z0-9_]{82}\\b",
    ["github_pat_"],
  ),
  format("github-oauth-token", "GitHub OAuth access token", "\\bgho_[A-Za-z0-9]{36}\\b", ["gho_"]),
  format(
    "github-app-token",
    "GitHub App user-to-server or server-to-server token",
    "\\b(?:ghu|ghs)_[A-Za-z0-9]{36}\\b",
    ["ghu_", "ghs_"],
  ),
  format("github-refresh-token", "GitHub refresh token", "\\bghr_[A-Za-z0-9]{36,76}\\b", ["ghr_"]),
  format("gitlab-pat", "GitLab personal access token", "\\bglpat-[A-Za-z0-9_-]{20,60}\\b", [
    "glpat-",
  ]),
  format(
    "gitlab-pipeline-trigger-token",
    "GitLab pipeline trigger token",
    "\\bglptt-[a-f0-9]{40}\\b",
    ["glptt-"],
  ),
  format(
    "gitlab-runner-registration-token",
    "GitLab runner registration token",
    "\\bGR1348941[A-Za-z0-9_-]{20}\\b",
    ["gr1348941"],
  ),
  format(
    "gitlab-runner-auth-token",
    "GitLab runner authentication token",
    "\\bglrt-[A-Za-z0-9_-]{20,60}\\b",
    ["glrt-"],
  ),
  format("gitlab-deploy-token", "GitLab deploy token", "\\bgldt-[A-Za-z0-9_-]{20}\\b", ["gldt-"]),
  format("gitlab-feed-token", "GitLab feed token", "\\bglft-[A-Za-z0-9_-]{20}\\b", ["glft-"]),
  format(
    "gitlab-oauth-app-secret",
    "GitLab OAuth application secret",
    "\\bgloas-[A-Za-z0-9_-]{64}\\b",
    ["gloas-"],
  ),
  format("gitlab-scim-token", "GitLab SCIM token", "\\bglsoat-[A-Za-z0-9_-]{20}\\b", ["glsoat-"]),
  format(
    "gitlab-incoming-mail-token",
    "GitLab incoming mail token",
    "\\bglimt-[A-Za-z0-9_-]{25}\\b",
    ["glimt-"],
  ),
  format(
    "gitlab-cicd-job-token",
    "GitLab CI/CD job token",
    "\\bglcbt-[A-Za-z0-9]{1,5}_[A-Za-z0-9_-]{20}\\b",
    ["glcbt-"],
  ),
  near(
    "bitbucket-client-secret",
    "Bitbucket OAuth client secret",
    ["bitbucket"],
    "[A-Za-z0-9=_-]{64}",
  ),
  format(
    "bitbucket-app-password",
    "Bitbucket app password / API token",
    "\\bATBB[A-Za-z0-9_=.-]{32}\\b",
    ["atbb"],
  ),
  format("atlassian-api-token", "Atlassian API token", "\\bATATT3[A-Za-z0-9_=-]{186}\\b", [
    "atatt3",
  ]),
  near(
    "atlassian-api-token-legacy",
    "Atlassian API token (legacy form)",
    ["atlassian", "confluence", "jira"],
    "[A-Za-z0-9]{24}",
  ),
  format(
    "circleci-token",
    "CircleCI personal API token",
    "\\bCCIPAT_[A-Za-z0-9]{22}_[a-f0-9]{40}\\b",
    ["ccipat_"],
  ),
  near("travis-ci-token", "Travis CI token", ["travis"], "[A-Za-z0-9]{22}"),
  format("buildkite-agent-token", "Buildkite API token", "\\bbkua_[a-f0-9]{40}\\b", ["bkua_"]),
  near("drone-ci-token", "Drone CI token", ["drone"], "[A-Za-z0-9]{32}"),
  format("jfrog-api-key", "JFrog Artifactory API key", "\\bAKCp[A-Za-z0-9]{69}\\b", ["akcp"]),
  near("jfrog-identity-token", "JFrog identity token", ["jfrog", "artifactory"], "[A-Za-z0-9]{64}"),
  format("npm-access-token", "npm access token", "\\bnpm_[A-Za-z0-9]{36}\\b", ["npm_"]),
  format("pypi-upload-token", "PyPI upload token", "\\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,400}", [
    "pypi-ageichlwas5vcmc",
  ]),
  format("rubygems-api-token", "RubyGems API token", "\\brubygems_[a-f0-9]{48}\\b", ["rubygems_"]),
  format("nuget-api-key", "NuGet API key", "\\boy2[a-z0-9]{43}\\b", ["oy2"]),
  format("clojars-api-token", "Clojars deploy token", "\\bCLOJARS_[a-z0-9]{60}\\b", ["clojars_"]),
  format("dockerhub-pat", "Docker Hub personal access token", "\\bdckr_pat_[A-Za-z0-9_-]{27}\\b", [
    "dckr_pat_",
  ]),
  format("sonarqube-token", "SonarQube / SonarCloud token", "\\b(?:squ|sqp|sqa)_[a-f0-9]{40}\\b", [
    "squ_",
    "sqp_",
    "sqa_",
  ]),
  near("snyk-api-token", "Snyk API token", ["snyk"], UUID),
  near("codecov-token", "Codecov upload token", ["codecov"], UUID),
  format("octopus-deploy-api-key", "Octopus Deploy API key", "\\bAPI-[A-Z0-9]{26}\\b", ["api-"]),
  format(
    "harness-api-key",
    "Harness personal or service account token",
    "\\b(?:pat|sat)\\.[A-Za-z0-9_-]{22}\\.[a-f0-9]{24}\\.[A-Za-z0-9]{20}\\b",
    ["pat.", "sat."],
  ),
  format("infracost-api-token", "Infracost API token", "\\bico-[A-Za-z0-9]{32}\\b", ["ico-"]),
  near(
    "sidekiq-secret",
    "Sidekiq Enterprise / Pro credentials",
    ["contribsys", "sidekiq"],
    "[a-f0-9]{8}:[a-f0-9]{8}",
  ),

  // --- observability and operations ---------------------------------------------------------
  format(
    "sentry-org-token",
    "Sentry organization auth token",
    "\\bsntrys_eyJ[A-Za-z0-9+/=_-]{60,400}",
    ["sntrys_"],
  ),
  format("sentry-user-token", "Sentry user auth token", "\\bsntryu_[a-f0-9]{64}\\b", ["sntryu_"]),
  format("grafana-api-key", "Grafana API key", "\\beyJrIjoi[A-Za-z0-9]{70,400}={0,2}", [
    "eyjrijoi",
  ]),
  format(
    "grafana-cloud-api-token",
    "Grafana Cloud API token",
    "\\bglc_[A-Za-z0-9+/]{32,400}={0,2}",
    ["glc_"],
  ),
  format(
    "grafana-service-account-token",
    "Grafana service account token",
    "\\bglsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8}\\b",
    ["glsa_"],
  ),
  near(
    "datadog-api-key",
    "Datadog API key",
    ["datadog", "dd_api_key", "dd-api-key"],
    "[a-f0-9]{32}",
  ),
  near(
    "datadog-app-key",
    "Datadog application key",
    ["dd_app_key", "dd-application-key", "datadog_app"],
    "[a-f0-9]{40}",
  ),
  format("new-relic-user-api-key", "New Relic user API key", "\\bNRAK-[A-Z0-9]{27}\\b", ["nrak-"]),
  format("new-relic-insert-key", "New Relic insights insert key", "\\bNRII-[A-Za-z0-9_-]{32}\\b", [
    "nrii-",
  ]),
  format("new-relic-browser-key", "New Relic browser API key", "\\bNRJS-[a-f0-9]{19}\\b", [
    "nrjs-",
  ]),
  format("new-relic-license-key", "New Relic license key", "\\b[a-f0-9]{36}NRAL\\b", ["nral"]),
  near("honeycomb-api-key", "Honeycomb API key", ["honeycomb"], "[A-Za-z0-9]{22,32}"),
  format(
    "dynatrace-api-token",
    "Dynatrace API token",
    "\\bdt0c01\\.[A-Z0-9]{24}\\.[A-Z0-9]{64}\\b",
    ["dt0c01."],
  ),
  near("pagerduty-api-key", "PagerDuty API key", ["pagerduty"], "[A-Za-z0-9_+-]{20}"),
  near("opsgenie-api-key", "Opsgenie API key", ["opsgenie"], UUID),
  near("rollbar-access-token", "Rollbar access token", ["rollbar"], "[a-f0-9]{32}"),
  near("bugsnag-api-key", "Bugsnag API key", ["bugsnag"], "[a-f0-9]{32}"),
  near(
    "launchdarkly-access-token",
    "LaunchDarkly access token",
    ["launchdarkly"],
    `(?:api|sdk)-${UUID}`,
  ),
  near("sumologic-access-key", "Sumo Logic access key", ["sumo"], "[A-Za-z0-9]{64}"),
  format("postman-api-token", "Postman API key", "\\bPMAK-[a-f0-9]{24}-[a-f0-9]{34}\\b", ["pmak-"]),
  format("readme-api-token", "ReadMe API token", "\\brdme_[a-z0-9]{70}\\b", ["rdme_"]),
  format("prefect-api-token", "Prefect API token", "\\bpnu_[A-Za-z0-9]{36}\\b", ["pnu_"]),

  // --- communication ------------------------------------------------------------------------
  format(
    "slack-bot-token",
    "Slack bot token",
    "\\bxoxb-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24,34}\\b",
    ["xoxb-"],
  ),
  format(
    "slack-user-token",
    "Slack user token",
    "\\bxox[pe]-(?:[0-9]{10,13}-){3}[A-Za-z0-9-]{28,34}\\b",
    ["xoxp-", "xoxe-"],
  ),
  format(
    "slack-app-token",
    "Slack app-level token",
    "\\bxapp-\\d-[A-Z0-9]{8,16}-\\d{8,16}-[a-z0-9]{32,80}\\b",
    ["xapp-"],
  ),
  format(
    "slack-config-access-token",
    "Slack configuration access token",
    "\\bxoxe\\.xox[bp]-\\d-[A-Z0-9]{163,166}\\b",
    ["xoxe.xox"],
  ),
  format(
    "slack-legacy-token",
    "Slack legacy workspace or session token",
    "\\bxox[os]-\\d{1,20}-\\d{1,20}-\\d{1,20}-[a-f0-9]{8,64}\\b",
    ["xoxo-", "xoxs-"],
  ),
  format(
    "slack-webhook-url",
    "Slack incoming webhook URL",
    "https://hooks\\.slack\\.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}",
    ["hooks.slack.com"],
  ),
  near(
    "discord-bot-token",
    "Discord bot token",
    ["discord"],
    "[MN][A-Za-z0-9]{23,25}\\.[A-Za-z0-9_-]{6}\\.[A-Za-z0-9_-]{27,38}",
  ),
  format(
    "discord-webhook-url",
    "Discord webhook URL",
    "https://(?:ptb\\.|canary\\.)?discord(?:app)?\\.com/api/webhooks/\\d{1,20}/[A-Za-z0-9_-]{60,68}",
    ["/api/webhooks/"],
  ),
  format(
    "teams-webhook-url",
    "Microsoft Teams incoming webhook URL",
    "https://[a-z0-9-]{1,64}\\.webhook\\.office\\.com/webhookb2/[a-z0-9@-]{1,128}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9-]{36}",
    ["webhook.office.com"],
  ),
  near(
    "telegram-bot-token",
    "Telegram bot token",
    ["telegram", "tg_bot", "bot_token"],
    "\\d{5,16}:A[A-Za-z0-9_-]{34}",
  ),
  format("twilio-api-key", "Twilio API key", "\\bSK[0-9a-f]{32}\\b", ["sk"]),
  near("twilio-auth-token", "Twilio auth token", ["twilio"], "[a-f0-9]{32}"),
  format(
    "sendgrid-api-key",
    "SendGrid API key",
    "\\bSG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}\\b",
    ["sg."],
  ),
  format("mailgun-private-api-token", "Mailgun private API key", "\\bkey-[a-f0-9]{32}\\b", [
    "key-",
  ]),
  near(
    "mailgun-signing-key",
    "Mailgun webhook signing key",
    ["mailgun"],
    "[a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8}",
  ),
  format("mailchimp-api-key", "Mailchimp API key", "\\b[a-f0-9]{32}-us\\d{1,2}\\b", ["-us"]),
  near("mailjet-api-key", "Mailjet API key", ["mailjet"], "[a-f0-9]{32}"),
  near("postmark-server-token", "Postmark server token", ["postmark"], UUID),
  format(
    "sendinblue-api-key",
    "Brevo (Sendinblue) API key",
    "\\bxkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}\\b",
    ["xkeysib-"],
  ),
  near("messagebird-api-token", "MessageBird API token", ["messagebird"], "[A-Za-z0-9]{25}"),
  near("intercom-access-token", "Intercom access token", ["intercom"], "[A-Za-z0-9=_-]{60}"),
  near("zendesk-secret-key", "Zendesk API token", ["zendesk"], "[A-Za-z0-9]{40}"),
  near("mattermost-access-token", "Mattermost access token", ["mattermost"], "[a-z0-9]{26}"),
  near("gitter-access-token", "Gitter access token", ["gitter"], "[a-z0-9_-]{40}"),

  // --- payments and commerce ----------------------------------------------------------------
  format(
    "stripe-secret-key",
    "Stripe secret or restricted key",
    "\\b(?:sk|rk)_(?:live|test|prod)_[A-Za-z0-9]{10,99}\\b",
    ["sk_live", "sk_test", "sk_prod", "rk_live", "rk_test", "rk_prod"],
  ),
  format(
    "stripe-webhook-secret",
    "Stripe webhook signing secret",
    "\\bwhsec_[A-Za-z0-9]{32,64}\\b",
    ["whsec_"],
  ),
  format(
    "square-access-token",
    "Square access token",
    "\\b(?:EAAA|sq0atp-)[A-Za-z0-9_-]{22,60}\\b",
    ["eaaa", "sq0atp-"],
  ),
  format("square-oauth-secret", "Square OAuth secret", "\\bsq0csp-[A-Za-z0-9_-]{43}\\b", [
    "sq0csp-",
  ]),
  format(
    "braintree-access-token",
    "PayPal Braintree access token",
    "\\baccess_token\\$production\\$[a-z0-9]{16}\\$[a-f0-9]{32}\\b",
    ["access_token$production$"],
  ),
  near("adyen-api-key", "Adyen API key", ["adyen"], "AQE[A-Za-z0-9_.+/=-]{80,200}"),
  format("shopify-access-token", "Shopify access token", "\\bshpat_[a-fA-F0-9]{32}\\b", ["shpat_"]),
  format(
    "shopify-custom-access-token",
    "Shopify custom app access token",
    "\\bshpca_[a-fA-F0-9]{32}\\b",
    ["shpca_"],
  ),
  format(
    "shopify-private-app-token",
    "Shopify private app access token",
    "\\bshppa_[a-fA-F0-9]{32}\\b",
    ["shppa_"],
  ),
  format("shopify-shared-secret", "Shopify shared secret", "\\bshpss_[a-fA-F0-9]{32}\\b", [
    "shpss_",
  ]),
  near("coinbase-access-token", "Coinbase access token", ["coinbase"], "[A-Za-z0-9_-]{64}"),
  near("plaid-secret", "Plaid secret", ["plaid"], "[a-f0-9]{30}"),
  format(
    "flutterwave-secret-key",
    "Flutterwave secret key",
    "\\bFLWSECK(?:_TEST)?-[a-h0-9]{32}-X\\b",
    ["flwseck"],
  ),
  near("gocardless-api-token", "GoCardless API token", ["gocardless"], "live_[A-Za-z0-9_=-]{40}"),
  format("shippo-api-token", "Shippo API token", "\\bshippo_(?:live|test)_[a-f0-9]{40}\\b", [
    "shippo_",
  ]),
  format("easypost-api-token", "EasyPost API key", "\\bEZ[AT]K[A-Za-z0-9]{54}\\b", [
    "ezak",
    "eztk",
  ]),
  near("lob-api-key", "Lob API key", ["lob"], "(?:live|test)_[a-f0-9]{35}"),
  format("duffel-api-token", "Duffel API token", "\\bduffel_(?:test|live)_[A-Za-z0-9_=-]{43}\\b", [
    "duffel_",
  ]),
  near("kraken-access-token", "Kraken API key", ["kraken"], "[A-Za-z0-9/=_+-]{80,90}"),

  // --- AI and ML platforms ------------------------------------------------------------------
  format(
    "openai-api-key",
    "OpenAI API key",
    "\\bsk-(?:proj-|svcacct-|admin-)?[A-Za-z0-9_-]{20,200}T3BlbkFJ[A-Za-z0-9_-]{20,200}",
    ["t3blbkfj"],
  ),
  format("anthropic-api-key", "Anthropic API key", "\\bsk-ant-api03-[A-Za-z0-9_-]{93}AA\\b", [
    "sk-ant-api03",
  ]),
  format(
    "anthropic-admin-key",
    "Anthropic admin API key",
    "\\bsk-ant-admin01-[A-Za-z0-9_-]{93}AA\\b",
    ["sk-ant-admin01"],
  ),
  format("huggingface-access-token", "Hugging Face access token", "\\bhf_[A-Za-z]{34}\\b", ["hf_"]),
  format("huggingface-org-token", "Hugging Face organization token", "\\bapi_org_[A-Za-z]{34}\\b", [
    "api_org_",
  ]),
  near("cohere-api-token", "Cohere API key", ["cohere", "co_api_key"], "[A-Za-z0-9]{40}"),
  format("replicate-api-token", "Replicate API token", "\\br8_[A-Za-z0-9]{37}\\b", ["r8_"]),
  format("groq-api-key", "Groq API key", "\\bgsk_[A-Za-z0-9]{52}\\b", ["gsk_"]),
  format("perplexity-api-key", "Perplexity API key", "\\bpplx-[A-Za-z0-9]{48}\\b", ["pplx-"]),
  format("xai-api-key", "xAI API key", "\\bxai-[A-Za-z0-9]{80}\\b", ["xai-"]),
  near("mistral-api-key", "Mistral API key", ["mistral"], "[A-Za-z0-9]{32}"),
  near("pinecone-api-key", "Pinecone API key", ["pinecone"], UUID),

  // --- productivity and SaaS ----------------------------------------------------------------
  format(
    "airtable-pat",
    "Airtable personal access token",
    "\\bpat[A-Za-z0-9]{14}\\.[a-f0-9]{64}\\b",
    ["pat"],
  ),
  near("airtable-api-key", "Airtable API key (legacy)", ["airtable"], "key[A-Za-z0-9]{14}"),
  near("asana-pat", "Asana personal access token", ["asana"], "[0-9]/[0-9]{16}:[A-Za-z0-9]{32}"),
  format("clickup-api-token", "ClickUp personal token", "\\bpk_[0-9]{6,9}_[A-Z0-9]{32}\\b", [
    "pk_",
  ]),
  near(
    "contentful-delivery-token",
    "Contentful delivery API token",
    ["contentful"],
    "[A-Za-z0-9_=-]{43}",
  ),
  format("dropbox-api-token", "Dropbox API token", "\\bsl\\.[A-Za-z0-9_-]{130,152}\\b", ["sl."]),
  format("figma-pat", "Figma personal access token", "\\bfigd_[A-Za-z0-9_-]{40}\\b", ["figd_"]),
  format("frameio-api-token", "Frame.io API token", "\\bfio-u-[A-Za-z0-9_=-]{64}\\b", ["fio-u-"]),
  format("linear-api-key", "Linear API key", "\\blin_api_[A-Za-z0-9]{40}\\b", ["lin_api_"]),
  format(
    "notion-integration-token",
    "Notion integration token",
    "\\b(?:secret_|ntn_)[A-Za-z0-9]{43,46}\\b",
    ["secret_", "ntn_"],
  ),
  near("okta-api-token", "Okta API token", ["okta"], "00[A-Za-z0-9_-]{40}"),
  format(
    "onepassword-service-account-token",
    "1Password service account token",
    "\\bops_eyJ[A-Za-z0-9+/=]{250,2000}",
    ["ops_eyj"],
  ),
  format(
    "onepassword-secret-key",
    "1Password account secret key",
    "\\bA3-[A-Z0-9]{6}-(?:[A-Z0-9]{11}|[A-Z0-9]{6}-[A-Z0-9]{5})-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b",
    ["a3-"],
  ),
  format("typeform-api-token", "Typeform API token", "\\btfp_[A-Za-z0-9_.=-]{59}\\b", ["tfp_"]),
  format("twitter-bearer-token", "Twitter / X bearer token", "\\bA{22}[A-Za-z0-9%]{30,200}", [
    "aaaaaaaaaaaaaaaaaaaaaa",
  ]),
  format(
    "facebook-access-token",
    "Facebook / Meta access token",
    "\\bEAACEdEose0cBA[A-Za-z0-9]{20,300}",
    ["eaacedeose0cba"],
  ),
  near(
    "facebook-app-secret",
    "Facebook / Meta app secret",
    ["facebook", "fb_app_secret"],
    "[a-f0-9]{32}",
  ),
  format(
    "mapbox-secret-token",
    "Mapbox secret token",
    "\\bsk\\.eyJ[A-Za-z0-9_-]{60,300}\\.[A-Za-z0-9_-]{22}\\b",
    ["sk.eyj"],
  ),
  near("algolia-admin-key", "Algolia admin API key", ["algolia"], "[a-f0-9]{32}"),
  near("hubspot-api-key", "HubSpot API key", ["hubspot"], UUID),
  near("trello-api-key", "Trello API key", ["trello"], "[A-Za-z0-9]{32}"),
  near("twitch-api-token", "Twitch API token", ["twitch"], "[a-z0-9]{30}"),
  near("etsy-access-token", "Etsy API key", ["etsy"], "[a-z0-9]{24}"),
  near("adafruit-api-key", "Adafruit IO key", ["adafruit"], "[a-z0-9_-]{32}"),
  near("beamer-api-token", "Beamer API key", ["beamer"], "b_[A-Za-z0-9=_-]{44}"),
  format(
    "authress-service-client-key",
    "Authress service client access key",
    "\\b(?:sc|ext|scauth|authress)_[a-z0-9]{5,30}\\.[a-z0-9]{4,6}\\.acc[_-][a-z0-9-]{10,32}\\.[a-z0-9+/_=-]{30,120}",
    [".acc_", ".acc-"],
  ),

  // --- keys, tokens and credential structures -----------------------------------------------
  format(
    "private-key",
    "PEM or PGP private key block",
    "-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----",
    ["-----begin"],
  ),
  format("putty-private-key", "PuTTY private key file", "PuTTY-User-Key-File-\\d{1,2}:", [
    "putty-user-key-file-",
  ]),
  format(
    "age-secret-key",
    "age encryption secret key",
    "\\bAGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}\\b",
    ["age-secret-key-1"],
  ),
  format(
    "jwt",
    "JSON Web Token",
    "\\beyJ[A-Za-z0-9_-]{10,2000}\\.eyJ[A-Za-z0-9_-]{10,4000}\\.[A-Za-z0-9_-]{10,2000}",
    ["eyj"],
  ),
  near(
    "crypto-private-key-hex",
    "Hex-encoded private key beside its keyword",
    ["private_key", "privatekey", "priv_key", "secret_key"],
    "(?:0x)?[a-fA-F0-9]{64}",
  ),
  uriCredential(
    "database-uri-credentials",
    "Password embedded in a database or broker connection URI",
    "postgres(?:ql)?|mysql|mariadb|mongodb(?:\\+srv)?|rediss?|amqps?|mssql|sqlserver|cockroachdb|clickhouse",
    [
      "postgres",
      "mysql",
      "mariadb",
      "mongodb",
      "redis",
      "amqp",
      "mssql",
      "sqlserver",
      "cockroachdb",
      "clickhouse",
    ],
  ),
  uriCredential(
    "url-basic-auth",
    "Password embedded in an HTTP(S) or FTP URL",
    "https?|ftps?|sftp",
    ["http", "ftp"],
  ),
  assignment("generic-password", "A quoted value assigned to a password-like name", PASSWORD_WORDS),
  assignment(
    "generic-api-key",
    "A quoted value assigned to a secret-, token- or key-like name",
    API_KEY_WORDS,
  ),
];

/**
 * What a `secrets` verdict can and cannot claim — the tooltip the Guardrails card renders.
 *
 * A constant rather than a sentence in the UI, so the card (#313) and anything else that renders
 * a secrets verdict say the same thing, and so the number of rules is counted rather than typed.
 */
export const SECRETS_RULESET_DISCLOSURE = {
  /** The version every `secrets` verdict records. */
  version: SECRETS_RULESET_VERSION,
  /** How many rules the version holds. */
  ruleCount: SECRET_RULES.length,
  /** The approximate share of real-world secrets a format ruleset recognises. */
  recallClass: "~70%",
  /** One sentence, for the tooltip. */
  summary:
    `Secrets ruleset ${SECRETS_RULESET_VERSION}: ${String(SECRET_RULES.length)} known credential ` +
    "formats plus keyword proximity, scanned over added diff lines.",
  /** What a pass does not mean. */
  limitation:
    "A pass means no known credential format was found — not that the diff holds no secrets. " +
    "High-entropy secrets with no recognisable format (roughly 30% of real-world leaks) are " +
    "not detected; verified scanning arrives with AR.5.",
} as const;

/**
 * Values the generic rules treat as placeholders rather than secrets.
 *
 * Anchored and whole: `changeme` is a placeholder and `changeme7Qx…` is not.
 */
const PLACEHOLDER =
  /^(?:\$\{[^}]*\}|\$\([^)]*\)|\{\{[^}]*\}\}|<[^>]*>|%[A-Za-z_]+%|\$[A-Za-z_][A-Za-z0-9_]*|x+|\*+|\.+|-+|(?:your|my|the|some)[-_]?[a-z_-]*|changeme|change[-_]me|password\d*|passwd|secret|example|sample|dummy|placeholder|redacted|test(?:ing)?\d*|fake|todo|null|none|undefined)$/i;

/**
 * Is a captured value a real candidate, or a placeholder / an identifier?
 *
 * @param value - What a generic rule captured.
 * @returns `true` when the value is worth reporting: not a known placeholder, and containing at
 *   least one digit and one letter — a secret that is all letters is a word, and one that is all
 *   digits is a number, and both are far more often code than credentials.
 */
export function isCandidateValue(value: string): boolean {
  return !PLACEHOLDER.test(value) && /[0-9]/.test(value) && /[A-Za-z]/.test(value);
}
