/**
 * Committed golden files a suite holds its output to — W.3
 * ([#179](https://github.com/NobuData/ouroboros/issues/179)).
 *
 * A golden file records what a function answered the last time a person looked, as JSON a
 * reviewer reads in a diff. Every run is compared against it, so a change that moves an answer —
 * a printer that writes one more line, a diagnostic that lands one line lower — fails naming the
 * file, the case and the command that regenerates it, rather than passing because the new answer
 * is consistent with itself.
 *
 * ```bash
 * OURO_UPDATE_GOLDENS=1 yarn jest <the suite that writes them>
 * ```
 *
 * rewrites the files from what that run produced, and the diff is the review. The variable is
 * refused where `CI` is set, so a pipeline can never bless its own output.
 *
 * It lives in `src/testing/` rather than beside the suites that use it because choosing between
 * comparing and rewriting reads the environment, which `eslint.config.mjs` allows only here.
 * `*.fixture.ts` is left out of the build.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

/** The variable that turns comparing into rewriting. */
export const UPDATE_GOLDENS = "OURO_UPDATE_GOLDENS";

/** What a golden file holds: a sentence for the reader, and each case's answer by name. */
export interface GoldenDocument {
  /** What the file records, and how to regenerate it. */
  readonly about: string;
  /** Each case's recorded answer, in the order the suite produced them. */
  readonly cases: Readonly<Record<string, unknown>>;
}

/**
 * Whether this run rewrites golden files rather than comparing against them.
 *
 * @param env - The environment to read. Defaults to the process's.
 * @returns `true` exactly when {@link UPDATE_GOLDENS} is `1`.
 * @throws {Error} When it is `1` and `CI` is set to anything but `false` or `0`: a pipeline that
 *   rewrote its goldens would pass whatever it produced.
 */
export function updatingGoldens(env: NodeJS.ProcessEnv = process.env): boolean {
  if (env[UPDATE_GOLDENS] !== "1") return false;

  const ci = env.CI;
  if (ci !== undefined && ci !== "" && ci !== "false" && ci !== "0") {
    throw new Error(
      `${UPDATE_GOLDENS}=1 is refused where CI is set: golden files are regenerated by a person, ` +
        "and the diff is reviewed.",
    );
  }

  return true;
}

/** One golden file, compared against or rewritten. */
export class GoldenFile {
  /** The cases this run recorded, when it rewrites. */
  private readonly recorded = new Map<string, unknown>();

  /** The committed file, once read. */
  private committed: GoldenDocument | undefined;

  /**
   * @param path - The file.
   * @param about - The sentence a rewrite writes as `about`.
   * @param regenerate - The command that rewrites the file, named in every failure.
   * @param updating - Whether this run rewrites. Defaults to {@link updatingGoldens}; a suite that
   *   must only ever compare passes `false`.
   */
  constructor(
    readonly path: string,
    private readonly about: string,
    private readonly regenerate: string,
    readonly updating: boolean = updatingGoldens(),
  ) {}

  /**
   * The case names the committed file records.
   *
   * @returns The names, in the file's order.
   * @throws {Error} When the file cannot be read or is not JSON.
   */
  names(): string[] {
    return Object.keys(this.read().cases);
  }

  /**
   * Hold one case's answer to the file — or, when rewriting, record it.
   *
   * @param name - The case.
   * @param actual - What the run produced. It is compared as JSON, since JSON is what the file
   *   holds: a property whose value is `undefined` is not there.
   * @throws {Error} When the file has no such case, or records something else. The message names
   *   the file, the case and the command that regenerates it, above Jest's diff.
   */
  hold(name: string, actual: unknown): void {
    const value = asJson(actual);

    if (this.updating) {
      this.recorded.set(name, value);
      return;
    }

    const { cases } = this.read();
    if (!Object.hasOwn(cases, name)) {
      throw new Error(`${this.label()} records no case "${name}". ${this.advice()}`);
    }

    try {
      expect(value).toEqual(cases[name]);
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      throw new Error(
        `${this.label()} no longer matches its case "${name}". ${this.advice()}\n\n${detail}`,
      );
    }
  }

  /**
   * Write what this run recorded, when it rewrites. Call it once, after every case was held.
   *
   * @returns Whether the file was written.
   */
  save(): boolean {
    if (!this.updating) return false;

    const document: GoldenDocument = {
      about: this.about,
      cases: Object.fromEntries(this.recorded),
    };
    writeFileSync(this.path, `${JSON.stringify(document, null, 2)}\n`, "utf8");
    return true;
  }

  /**
   * The committed file.
   *
   * @returns It, read on first use.
   */
  private read(): GoldenDocument {
    this.committed ??= JSON.parse(readFileSync(this.path, "utf8")) as GoldenDocument;
    return this.committed;
  }

  /** How a failure names the file. */
  private label(): string {
    return `The golden file ${basename(this.path)}`;
  }

  /** What a failure tells the reader to do. */
  private advice(): string {
    return (
      "If the change that moved it is intended — a grammar or printer change, say — regenerate " +
      `it with \`${this.regenerate}\` and review the diff. If it is not, the output has drifted.`
    );
  }
}

/**
 * A value as JSON would give it back.
 *
 * @param value - Anything `JSON.stringify` accepts.
 * @returns The parsed round trip, or `null` for a value JSON cannot hold at all.
 */
function asJson(value: unknown): unknown {
  const text = JSON.stringify(value);
  return text === undefined ? null : (JSON.parse(text) as unknown);
}
