import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import { SECTIONS } from "./site.constants";

// This runs in Node.js — no browser APIs or JSX here.

/**
 * The site's sidebars — exactly three, one per section (roadmap decision D2).
 *
 * Each sidebar is generated from its section's folder under `docs/`: pages are ordered by
 * their `sidebar_position` front matter and grouped by subfolders, whose `_category_.json`
 * gives the group's label, position and landing page. Adding a page therefore needs no
 * edit here — drop the file into the right folder. A page outside the three folders (only
 * the home page, `docs/index.md`) belongs to no sidebar.
 */
const sidebars: SidebarsConfig = Object.fromEntries(
  SECTIONS.map((section) => [section.sidebarId, [{ type: "autogenerated", dirName: section.dir }]]),
);

export default sidebars;
